lib/maintainers.nix
pkgs/applications/editors/fte/default.nix
pkgs/top-level/all-packages.nix

Package FTE (straightforward translation from [Arch Linux](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fte))
on non-NixOS)
---

fte: init at 0.50.02

---

nixos/modules/module-list.nix
nixos/modules/services/networking/miredo.nix
pkgs/tools/networking/miredo/default.nix
pkgs/top-level/all-packages.nix

Provide IPv6 where it is not available natively, including machines behind NAT.
I did not created the "miredo" user and group as the daemon consists of two processes: one requires root privileges and another runs under user "nobody".
on non-NixOS)
---

miredo: init at 1.2.6

---

nixos/modules/services/networking/miredo.nix

Fixed path to ```kill```
on non-NixOS)
---

miredo: fix path to "kill"

---

nixos/modules/services/x11/hardware/synaptics.nix

Fix dead symlink.
the file in [xf86-input-synaptics-1.9.0.tar.bz2](https://www.x.org/releases/individual/driver/xf86-input-synaptics-1.9.0.tar.bz2) has name ```70-synaptics.conf```, not ```50-synaptics.conf```.
on non-NixOS)
---

synaptics: fix broken symlink

---

pkgs/desktops/xfce/default.nix
pkgs/desktops/xfce/panel-plugins/xfce4-windowck-plugin.nix

Set of two plugins which allows you to put the maximized window title and windows buttons on the panel
on non-NixOS)
---

xfce4-windowck-plugin: init at 0.4.4

---

nixos/modules/services/web-servers/apache-httpd/trac.nix

setuptools is not a top-level package
on non-NixOS)
---

httpd: setuptools is not a top-level package

---

pkgs/applications/networking/browsers/chromium/default.nix
pkgs/applications/networking/browsers/google-chrome/default.nix

It is convenient to be able to ```.override``` chromium package in a way so it is always start with given [command line arguments](http://peter.sh/experiments/chromium-command-line-switches/), e.g ```--disable-gpu``` irregardless of how chromium is launched: by clicking on a toolbar icon, via ```xdg-open```, or from a some shell script.
on non-NixOS)
---

chromium, google-chrome: add commandLineArgs

---

pkgs/desktops/xfce/applications/mousepad.nix

Let ```xfce.mousepad``` use configuration in ```~/.config/Mousepad``` instead of ```gconf```
Fixes #12016 #14862 #21725
The error message about absence of 'none' color scheme in GtkSourceView is still here (it would require a bigger [patch](https://bugzilla.xfce.org/show_bug.cgi?id=11663)). but now it does result in the CPU-consuming infinite loop.
on non-NixOS)
---

xfce.mousepad: use keyfile instead of gconf

---

pkgs/applications/networking/browsers/chromium/plugins.nix

https://github.com/NixOS/nixpkgs/commit/ce11097b712c9415952a5bd6fce6184c7b923c20 missed one file  with old vulnerable flash version

flashplayer: 24.0.0.186 -> 24.0.0.194

---

pkgs/development/compilers/scala/2.10.nix
pkgs/development/compilers/scala/2.11.nix
pkgs/top-level/all-packages.nix

1. ```pkgs.scala_2_11``` pointed to scala 2.12
2. scala 2.11 was not in nixpkgs at all. there were 2.9, 2.10, 2.12
3. bash scripts (such as ```scalac```) rely on ```coreutils```, ```gnugrep``` and environment variable ```JAVA_HOME``` 
4. minor version updated from 2.10.5 to 2.10.6 in 2.10 branch 
on non-NixOS)
---

scala: fix versions and $PATH

---

nixos/modules/services/networking/miredo.nix

Network is down when ```nixos-rebuild``` restarts ```miredo``` service.
It results in ```miredo-checkconf``` failure.
The failure to restart ```miredo``` aborts ```nixos-rebuild```.
```
Jan 12 14:10:59 nixos miredo-checkconf[13432]: Invalid host name “teredo.remlab.net” at line 2: Temporary failure in name resolution
Jan 12 14:10:59 nixos miredo-checkconf[13432]: Server address not specified
Jan 12 14:10:59 nixos miredo-checkconf[13432]: Fatal configuration error
```
on non-NixOS)
---

miredo: do not run miredo-checkconf

---

pkgs/servers/x11/xorg/overrides.nix
pkgs/servers/x11/xquartz/default.nix
pkgs/servers/x11/xquartz/startx
pkgs/tools/X11/bumblebee/default.nix
pkgs/tools/X11/bumblebee/nixos.patch
pkgs/tools/X11/xpra/default.nix
pkgs/tools/X11/xpra/gtk3.nix
pkgs/tools/misc/xvfb-run/default.nix

Xorg binaries contain inside the wrong path ```${xorg.xserver}/share/X11/xkb``` instead of ```${xorg.xkeyboardconfig}/share/X11/xkb```.
This forces every program launching any of the ```Xorg``` binaries to take care on passing a command like parameter ```-xkbdir ${xkeyboard_config}/etc/X11/xkb``` overriding the wrong path compiled into binaries:[1](https://github.com/NixOS/nixpkgs/blob/68ab32fbf880787a6e7340d749483cdc743b4b96/pkgs/servers/x11/xquartz/startx#L220) [2](https://github.com/NixOS/nixpkgs/blob/68ab32fbf880787a6e7340d749483cdc743b4b96/pkgs/tools/misc/xvfb-run/default.nix#L15) [3](https://github.com/NixOS/nixpkgs/blob/68ab32fbf880787a6e7340d749483cdc743b4b96/pkgs/tools/X11/bumblebee/nixos.patch#L57) [4](https://github.com/NixOS/nixpkgs/blob/68ab32fbf880787a6e7340d749483cdc743b4b96 …

xorg.xserver: configure --with-xkb-path=

---

pkgs/applications/virtualization/virt-top/default.nix
pkgs/development/ocaml-modules/curses/default.nix
pkgs/development/ocaml-modules/ocaml-gettext/default.nix
pkgs/development/ocaml-modules/ocaml-libvirt/default.nix
pkgs/top-level/all-packages.nix
pkgs/top-level/ocaml-packages.nix

A top-like utility for showing stats of virtualized domains
on non-NixOS)
---

virt-top: init at 1.0.8

---

pkgs/data/fonts/liberastika/default.nix
pkgs/top-level/all-packages.nix

Liberation Sans fork with improved cyrillic support
on non-NixOS)
---

liberastika: init at 1.1.5

---

pkgs/top-level/all-packages.nix

minor fix for issue #22439: Scala 2.12 requires JRE8

scala 2.12 requires jre8

---

nixos/modules/virtualisation/lxc.nix

LXC containers do not start if directory ```/var/lib/lxc/rootfs``` is not present.
Fixes #23604
on non-NixOS)
---

lxc: ensure directory /var/lib/lxc/rootfs

---

pkgs/applications/window-managers/icewm/default.nix

On non-NixOS Linuxes ```IceWM``` finds its config files in following directories: ```~/.icewm``` then ```/etc/icewm``` then ```${pkgs.icewm}/share/icewm```
On NixOS the second directory is ```${pkgs.icewm}/etc/icewm``` which is not exist nor writable.
This patch restores the usual sequence.
Why placing configs into ```/etc/icewm``` could be useful?
IceWM is often used with ```test-driver``` and it would allow to write in the tests something like 
```
environment.etc."icewm/preferences".text = ''
NetworkStatusDevice="eth0 eth1"
'';
```
and have graphs of both network interfaces on the screenshots.
on non-NixOS) …

icewm: fix CFGDIR

---

pkgs/applications/virtualization/virt-manager/default.nix

virt-manager: 1.4.0 -> 1.4.1

---

pkgs/data/fonts/babelstone-han/default.nix
pkgs/top-level/all-packages.nix

Most complete Chinese font (it contains characters which are absent in other fonts, even in ```Google Noto```)
on non-NixOS)
---

babelstone-han: init at 9.0.2

---

pkgs/applications/misc/far2l/default.nix
pkgs/top-level/all-packages.nix

Linux port of [Far](https://en.wikipedia.org/wiki/Far_Manager), an orthodox file manager, 
on non-NixOS)
---

far2l: init at 2.1

---

pkgs/os-specific/linux/kernel/manual-config.nix

```installPhase``` removes (using ```rm``` and ```mv```) files produced on ```buildPhase``` thus making impossible iterative development in ```nix-shell``` style.
So ```rm``` is removed and ```mv``` replaced with ```cp```, also the code is simplified a bit.
```chmod -w filename``` replaced with ```chmod u-w filename``` becase the former fails on files with access mask ```664```:
```chmod: filename: new permissions are r--rw-r--, not r--r--r--```. There are no such files in the kernel source tarball, but I accidentally made some during development. 
on non-NixOS)
---

kernel: do not remove .o files on installPhase

---

pkgs/os-specific/linux/openvswitch/default.nix

Minor bugfix update in LTS 2.5.x branch (the latest version now is 2.7.0)
on non-NixOS)
---

openvswitch: 2.5.0 -> 2.5.2

---

pkgs/desktops/xfce/art/xfwm4-themes.nix
pkgs/desktops/xfce/default.nix

Additional themes for XFCE.
The package is 5 years old and has version of 4.10 (actual XFCE is 4.12), yet there is nothing to update, it is basically graphic files of classic themes like Motif, Windows95, WindowsXP, etc
Ubuntu and other distros has the [same](http://packages.ubuntu.com/search?keywords=xfwm4-themes) version 
It is not included in default XFCE of NixOS and won't bloat any existing installation.
```pkgs.xfce.xfwm4themes``` should be explicitly added into ```environment.systemPackages``` for  extra themes to appear in the ```Window Manager``` settings box:
on non-NixOS)
---

xfwm4-themes: init at 4.10.0

---

pkgs/development/libraries/hivex/default.nix
pkgs/development/libraries/hivex/hivex-syms.patch
pkgs/development/libraries/libguestfs/default.nix
pkgs/development/libraries/libguestfs/libguestfs-syms.patch
pkgs/development/ocaml-modules/ocaml-libvirt/default.nix

Newer version, stable branch, more utilities.
on non-NixOS)
---

libguestfs: 1.29.5 -> 1.36.3

---

pkgs/applications/virtualization/qemu/default.nix
pkgs/applications/virtualization/qemu/no-etc-install.patch

minor release.
some bugfixes and security patches are applied, but not all.
it also includes @dezgeg's patch mentioned in https://github.com/NixOS/nixpkgs/issues/23957#issuecomment-288117708
on non-NixOS)
---

qemu: 2.8.0 -> 2.8.1

---

pkgs/applications/misc/dockbarx/default.nix
pkgs/desktops/xfce/default.nix
pkgs/desktops/xfce/panel-plugins/xfce4-dockbarx-plugin.nix
pkgs/top-level/all-packages.nix

A plugin that embeds DockbarX into Xfce4-panel
on non-NixOS)
---

xfce4-dockbarx-plugin: init at 0.5

---

nixos/modules/module-list.nix
nixos/modules/services/networking/xrdp.nix
nixos/tests/xrdp.nix
pkgs/applications/networking/remote/xrdp/default.nix
pkgs/top-level/all-packages.nix

RDP server (remote desktop which is good for high latency connections).
nix package + nixos module + test script
on non-NixOS)
---

xrdp: init at 0.9.2

---

pkgs/development/compilers/reason/default.nix
pkgs/development/ocaml-modules/merlin_extend/default.nix
pkgs/development/ocaml-modules/ocaml-migrate-parsetree/default.nix
pkgs/development/ocaml-modules/ppx_tools_versioned/default.nix
pkgs/development/tools/ocaml/utop/default.nix
pkgs/top-level/all-packages.nix
pkgs/top-level/ocaml-packages.nix

Facebook's frontend for Ocaml.
on non-NixOS)
Tested: REPL and compiler.
Not tested: integration with emacs and merlin.
Additional changes: 
* bumped minor versions of ```ocaml-migrate-parsetree``` and ```jbuilder``` (it allows compilation with  ocaml-```4.02```)
* fixed escaping in non-standard wrapper in ```utop``` (17.03 uses good old ```makeWrapper``` and has no problem, only master branch has the problem....). ```Reason```'s REPL depends on this bugfix.
* ~~```jbuilder``` moved from ```all-packages.nix``` to ```ocaml-packages.nix``` to be among other Jane Street's builders.~~
---

reason: init at 1.13.3

---

pkgs/desktops/xfce/applications/xfce4-screenshooter.nix

Without this fix upload to ```Imgur``` fails with ```"TLS/SSL support not available; install glib-networking"```
on non-NixOS)
---

xfce4-screenshooter: add glib_networking dependency

---

pkgs/applications/networking/browsers/google-chrome/default.nix

closure size.
```google-chrome``` depends on ```gcc``` compiler (twice: as ```stdenv.cc.cc``` and ```gcc```) although it needs only ```libstdc++.so.6``` from ```gcc.lib```
on non-NixOS)
---

google-chrome: remove dependency on gcc

---

nixos/modules/services/networking/xrdp.nix

prevent ```nixos-rebuild``` from restarting ```xrdp-sesman``` which is kind of ```display-manager```: the service is parent for X11 apps.
on non-NixOS)
---

xrdp: do not restart xrdp-sesman on nixos-rebuild

---

pkgs/tools/graphics/pngquant/default.nix

version update
on non-NixOS)
---

pngquant: 2.6.0 -> 2.9.1

---

pkgs/tools/graphics/pngquant/default.nix

restored 'patchShebangs' because build [failed on Hydra](https://hydra.nixos.org/build/52569452)
on non-NixOS)
---

pngquant: restored 'patchShebangs' because build failed on Hydra

---

pkgs/development/libraries/half/default.nix
pkgs/top-level/all-packages.nix

Header-only C++ library (one .hpp file).
Having it in nixpkgs made it discoverable by cmake, etc
on non-NixOS)
---

half: init at 1.12.0

---

pkgs/applications/misc/far2l/default.nix

Add .desktop file and icons.
removed unnecessary dependency on ```xterm```.
on non-NixOS)
---

far2l: add .desktop file

---

pkgs/tools/X11/xdg-utils/default.nix

xdg_utils: fix #25511 (broken sed magic)
on non-NixOS)
---

xdg_utils: fix #25511 (broken sed magic)

---

pkgs/desktops/xfce/default.nix
pkgs/desktops/xfce/panel-plugins/xfce4-namebar-plugin.nix

A less buggy alternative to ```xfce4_windowck_plugin```
on non-NixOS)
---

xfce4_namebar_plugin: init at 0.3.1

---

pkgs/desktops/xfce/panel-plugins/xfce4-dockbarx-plugin.nix

Fix #26379
regression after https://github.com/NixOS/nixpkgs/commit/aa86d9fa7a93023f6c54f45631505375dc628b91
@FRidh if you insist on https://github.com/NixOS/nixpkgs/commit/aa86d9fa7a93023f6c54f45631505375dc628b91 please review all 41 usages of ```wrapPythonPrograms```. Some of them might have something to wrap in other directories than ```$out/bin```. It is already the second found regression of that commit (another is https://github.com/NixOS/nixpkgs/pull/26375)

xfce4-dockbarx-plugin: fix #26379

---

pkgs/data/misc/nixos-artwork/wallpapers.nix

Fixes #26565
After #26460 ```nixos-rebuild``` fails with error
```
cannot copy /nix/store/sj1psbij342r12xv61fx6jcxwapkkj3g-gnome-dark-2015-02-27/share/artwork/gnome/Gnome_Dark.png to /boot
```
because the filename contains nix hash:
```
/etc/nixos$ ls -l /nix/store/sj1psbij342r12xv61fx6jcxwapkkj3g-gnome-dark-2015-02-27/share/artwork/gnome                                               
total 0                                                                                                                                               
lrwxrwxrwx 3 root root 58 Jan  1  1970 1vhgkmby6lkm6qz3kv6pmzylv1599z7y-Gnome_Dark.png -> /nix/store/1vhgkmby6lkm6qz3kv6pmzylv1599z7y-Gnome_Dark.png  
```

nixos-artwork: do not leak nix hashes to filenames in /share/artwork/gnome/

---

pkgs/applications/networking/browsers/vivaldi/default.nix

vivaldi: fix space in sha256

---

pkgs/development/tools/build-managers/sbt/scala-native.nix
pkgs/top-level/all-packages.nix

That rare case of upstream [supporting nix](https://github.com/scala-native/scala-native/blob/master/bin/scala-native.nix):  :)
But their solution is to [run ```sbt``` in ```nix-shell```](https://github.com/scala-native/scala-native/blob/master/docs/user/setup.rst) with prepared ```buildInputs``` list
As ```sbt``` is the only program to run in this environment (all the rest is launched by ```sbt```), I think it would be nicer just to wrap ```sbt``` enriching it with optional posibility to build ```scala-native``` targets even without ```nix-shell```
Just replace ```sbt``` package with ```sbt-with-scala-native``` and it will be able to find all libraries required for native builds.
cc: @MasseGuillaume 
([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on …

sbt: support scala-native

---

pkgs/applications/editors/jetbrains/default.nix

jetbrains.{ruby-mine,webstorm,datagrip,phpstorm}: 2017.1 -> 2017.1.4

---

pkgs/applications/editors/jetbrains/default.nix
pkgs/applications/editors/jetbrains/update.pl

A script which updates ```version``` and ```sha256``` of Jetbrains products from https://www.jetbrains.com/updates/updates.xml in a bulk way as @chris-martin proposed in https://github.com/NixOS/nixpkgs/issues/24643
Fixes https://github.com/NixOS/nixpkgs/issues/24643
Derivations of some legacy products have ```update-channel = null;```, although there are corresponding legacy channels like ```IDEA15_Release``` The problem is the proposed  versions in those channels are much newer than ```15.x```, something like ```2017.1```.
Setting ```update-channel = null;``` prevents them from being updated.

jetbrains: update script

---

pkgs/development/tools/nailgun/default.nix
pkgs/top-level/all-packages.nix

It speeds up JVM startup by keeping it in memory between launches of Java programs.
on non-NixOS)
---

nailgun: init at 0.9.1

---

pkgs/servers/sql/postgresql/plv8/default.nix
pkgs/top-level/all-packages.nix

To write PostgreSQL stored procedures in JavaScript.
on non-NixOS)
---

plv8: init at 2.0.3

---

pkgs/applications/editors/eclipse/build-eclipse.nix
pkgs/applications/editors/eclipse/default.nix
pkgs/applications/editors/emacs/default.nix
pkgs/applications/networking/browsers/dwb/default.nix
pkgs/applications/networking/mailreaders/astroid/default.nix
pkgs/applications/networking/mailreaders/claws-mail/default.nix
pkgs/applications/video/miro/default.nix
pkgs/desktops/gnome-3/3.22/default.nix
pkgs/development/haskell-modules/configuration-nix.nix
pkgs/development/libraries/wxwidgets/3.0/default.nix
pkgs/tools/networking/mu/default.nix
pkgs/top-level/all-packages.nix
pkgs/top-level/python-packages.nix

It was confusing whether ```2``` in ```webkitgtk2``` means version of ```webkitgtk``` or version of ```gtk```
It also made clear that [wxwidgets depends on outdated and insecure webkitgtk 2.4](https://github.com/NixOS/nixpkgs/compare/master...volth:webkitgtk-naming?expand=1#diff-8be06145e2ed680686ba6be2c686062b) which might have to be fixed.
on non-NixOS)
---

rename webkitgtk24x⇒webkitgtk24x-gtk3; webkitgtk2⇒webkitgtk24x-gtk2

---

pkgs/tools/security/certstrap/default.nix
pkgs/top-level/all-packages.nix

Square's tools to bootstrap CAs, certificate requests, and signed certificates
on non-NixOS)
---

certstrap: init at 1.0.1

---

pkgs/tools/system/collectd/default.nix

1. Added ```--localstatedir=/var``` to ```configureFlags```
Otherwise the default locations of ephemeral files and sockets are in the nix store:
```
./collectdctl: missing command
Usage: ./collectdctl [options] <command> [cmd options]
Available options:
-s       Path to collectd's UNIX socket.
Default: /nix/store/6gz0k2p2v0n3aw7v8hyjf05qkr2dbzki-collectd-5.7.2/var/run/collectd-unixsock
-h       Display this help and exit.
```
2. jars placed to ```$out/share/java``` (where the nix java hook can find them)

collectd: fix configureFlags and jar location

---

nixos/modules/misc/ids.nix
nixos/modules/services/monitoring/collectd.nix

* removed pid-file support, it is needless to run collectd as systemd service
* removed static user id, as all the files reowned on the service start
* <s>added ambient capabilities for ping and smart (hdd health) functions</s> removed
on non-NixOS)
---

collectd service: minor refactoring

---

nixos/modules/module-list.nix
nixos/modules/services/web-servers/lighttpd/collectd.nix

To display collectd graphs on the web
on non-NixOS)
---

lighttpd: add collectd submodule

---

pkgs/applications/audio/sisco.lv2/default.nix
pkgs/build-support/fetchgit/default.nix
pkgs/build-support/fetchgit/gitrepotoname.nix
pkgs/build-support/fetchgit/nix-prefetch-git
pkgs/development/interpreters/ruby/default.nix
pkgs/servers/mail/postfix/pfixtools.nix
pkgs/tools/networking/email/default.nix
pkgs/top-level/all-packages.nix

Fixes #21620
Both failed examples from #21620 work well now:
```nix
fetchFromGitHub {
owner = "aerospike";
repo = "aerospike-server";
rev = "3.14.0.1";
sha256 = "1kzkwvir9j9jdlwp8gi9p3wkv3qhbrn62x1mb1xlnrdc7rk32kyn";
fetchSubmodules = true;
}
```
which failed with ```Bad commit hash or bad reference```
```nix
fetchFromGitHub {
owner = "aerospike";
repo = "aerospike-server";
rev = "refs/tags/3.14.0.1";
sha256 = "1kzkwvir9j9jdlwp8gi9p3wkv3qhbrn62x1mb1xlnrdc7rk32kyn";
fetchSubmodules = true;
}
```
which failed with ```invalid character ‘/’ in name ‘aerospike-server-refs/tags/3.14.0.1-src’```
1. use the same ```urlToName``` for ```fetchgit``` and ```fetchFromGitHub``` to avoid producing nix store names containing forbidden characters (for example ```/```) by simplified implementation used in …

fetchFromGitHub: fix fetchSubmodules when revision is not hexadecimal

---

nixos/modules/misc/ids.nix
nixos/modules/module-list.nix
nixos/modules/services/security/vault.nix
pkgs/tools/security/vault/default.nix

fork of PR #26130 with 
* updated to version 0.7.3
* run service under an unprivileged user instead of root
* <s>generate self-signed TLS certificate if certificate file does exist when the service starts (so ```services.vault.enable = true;``` in ```configuration.nix``` is enough to get some minimal setup up and running)</s> feature removed, see comments
* removed rarely used ```tls_*``` options (they could be set in ```extraConfig```)
* fixed typo (inMemory -> inmem)
* option names made camelCased
* build as a Makefile project, not a Go package
on non-NixOS)
---

vault: 0.6.5 -> 0.7.3 with service

---

nixos/modules/profiles/all-hardware.nix

NixOS does not boot in VMware guest without these modules

all-hardware.nix: add VMware support.

---

pkgs/development/libraries/libvirt/default.nix
pkgs/top-level/python-packages.nix

Minor update
on non-NixOS)
---

libvirt: 3.1.0 -> 3.5.0

---

nixos/modules/services/misc/zookeeper.nix

It could have chars to escape, for example
```extraCmdLineOptions = [ "-Xmx512m" "-Xms512m" "-XX:OnOutOfMemoryError=kill -9 %p" ];```

nixos/zookeeper: escape cfg.extraCmdLineOptions

---

nixos/modules/services/networking/tinc.nix

Now user can execute e.g. ```sudo tinc.netname dump nodes```
on non-NixOS)
---

nixos/tinc: add CLI tools to the $PATH

---

nixos/modules/services/networking/tinc.nix
pkgs/tools/networking/tinc/pre.nix

The problem is: on ```nixos-rebuild```, Tinc stops working and spams log with
```
Jul 27 05:38:20 x1 tinc.lan-start[1054]: Error while reading from Linux tun/tap device (tun mode) /dev/net/tun: File descriptor in bad state
Jul 27 05:38:20 x1 tinc.lan-start[1054]: Error while reading from Linux tun/tap device (tun mode) /dev/net/tun: File descriptor in bad state
Jul 27 05:38:20 x1 systemd-journald[599]: Suppressed 489664 messages from /system.slice/tinc.lan.service
```
PR has been submitted to upstream and accepted: https://github.com/gsliepen/tinc/issues/146
Please check what applies. Note that these are not hard requirements but mereley serve as information for reviewers.
or option …

tinc_pre: avoid infinite loop with EBADFD on network restart

---

nixos/modules/services/networking/tinc.nix

```restartTriggers``` pointed to the constant files in ```/nix/store/``` and had to effect.

nixos/tinc: remove restartTriggers

---

nixos/modules/services/networking/tinc.nix

Fixes https://github.com/NixOS/nixpkgs/issues/27397

tinc: allow the daemon to write to files in /etc/tinc/${network}/hosts

---

pkgs/applications/networking/remote/xrdp/default.nix

It created ```/nix/store/vdhg5dclbnhfhpad40zvxcgi1hsvnavy-xrdp-0.9.3./do-not-install```

xrdp: abs path to garbage directory

---

pkgs/development/compilers/oraclejdk/jdk-linux-base.nix

Nothing should change unless you override ```gtk2``` or ```gnome2.gtk``` in overlays so they become different

orackejdk: untie from gnome2

---

pkgs/data/fonts/babelstone-han/default.nix

Update version because the old version was removed from the upstream site.
Also the derivation was made fixed-output because the font is big and there is no point to have different outputs for each platform (https://github.com/NixOS/nixpkgs/issues/27754)

babelstone-han: 9.0.2 -> 10.0.0

---

pkgs/data/fonts/roboto/default.nix

roboto: make the font derivation fixed-output

---

pkgs/data/fonts/mro-unicode/default.nix

mro-unicode: make the font derivation fixed-output

---

nixos/modules/services/networking/tinc.nix

```Tinc```'s pidfile has more info than just a pid
```
12209 7BD4A657B4A04364D268D188A0F4AA972A05247D802149246BBE1F1E689CABA1 127.0.0.1 port 656
```
```systemd``` fails to parse it.
It results in long (re)start times when ```systemd``` waits for a correct pidfile to appear.
It is especially visible if you set ```Type="forking"``` (and remove ```-D``` from command line):
the Tinc service will stuck in the ```activating``` state and never reach the ```active``` state.

nixos/tinc: do not tell systemd where is pidfile

---

pkgs/data/fonts/opensans-ttf/default.nix

opensans-ttf: dead link fixed

---

pkgs/data/fonts/cabin/default.nix

cabin: make the font derivation fixed-output

---

pkgs/data/fonts/fira-code/default.nix

fira-code: make the font derivation fixed-output

---

pkgs/data/fonts/fira-code/symbols.nix

fira-code-symbols: make the font derivation fixed-output

---

pkgs/data/fonts/clearlyU/default.nix
pkgs/data/fonts/dina-pcf/default.nix
pkgs/data/fonts/dosemu-fonts/default.nix
pkgs/data/fonts/envypn-font/default.nix
pkgs/data/fonts/gohufont/default.nix
pkgs/data/fonts/proggyfonts/default.nix
pkgs/data/fonts/tewi/default.nix
pkgs/data/fonts/ucs-fonts/default.nix
pkgs/data/fonts/uni-vga/default.nix
pkgs/data/fonts/unifont/default.nix

follow up https://github.com/NixOS/nixpkgs/pull/28161
fonts refactorings, the group of not so trivial fonts.
I decided to keep post-download ```sha256``` in this group to ease debugging why ```outputHash``` may be not stable. it could be removed later to reduce the code size.
cc: @fpletz @Mic92 
This PR does not depend on https://github.com/NixOS/nixpkgs/pull/28161 and may be merged earlier.

data/fonts: make derivations fixed-outputs (group 2)

---

pkgs/top-level/all-packages.nix

gdouros: x.xx -> x.17

---

nixos/modules/virtualisation/libvirtd.nix
pkgs/development/libraries/libvirt/default.nix
pkgs/top-level/python-packages.nix

If you migrate existing VMs to this version and they have in XML-file something like
```<emulator>/nix/store/..../qemu-kvm</emulator>``` or
```<emulator>/nix/store/..../libvirt_lxc</emulator>```
you will have to change it to 
```<emulator>/run/libvirt/nix-emulators/qemu-kvm</emulator>``` or
```<emulator>/run/libvirt/nix-emulators/libvirt_lxc</emulator>```
**manually**, otherwise your VMs stop working when ```qemu``` derivation will be garbage collected.
Why not automatically?
Because /nix/store path in ```<emulator>``` could be intentional, it is not an error.
You could want to use dev or patched or legacy ```qemu``` and explicitly set its path. But then it is up to you to protect that custom ```qemu``` from GC. https://github.com/NixOS/nixpkgs/issues/27857 covers some other problems of …

libvirt: 3.5.0 -> 3.6.0

---

pkgs/tools/misc/fontforge/default.nix
pkgs/tools/misc/fontforge/fontforge-20140813-use-system-uthash.patch
pkgs/tools/misc/fontforge/fontforge-fonttools.nix

@7c6f434c: should it be in sync with ```fontforge```?
Note there are two different ```$SOURCE_DATE_EPOCH``` - when fontforge is compiled from the sources, and when fontforge compiles fonts. It is about the latter.
For example, current ```pkgs.inconsolata-lgc``` and ```pkgs.pkgsi686Linux.inconsolata-lgc``` are very different, even in the file sizes.
I hope supporting pre-SSE i686 platforms (older than Pentium-4 of year 2001) is not on the agenda? if so, then ```softfloat``` would be the option.

fontforge: 20160404 -> 20170730 + support reproducible builds of fonts

---

pkgs/development/mobile/androidenv/androidndk.nix
pkgs/development/mobile/androidenv/androidndk_r8e.nix

Build scripts of some Android programs run ```$ANDROID_NDK/libexec/*/ndk-build``` where scripts are not wrapped
This PR puts wrapping of scripts before making symlinks in ```$out/bin```, so both ```$ANDROID_NDK/bin/ndk-build``` and ```$ANDROID_NDK/libexec/*/ndk-build``` are wrapped.

androidndk: wrap scripts in $out/libexec

---

pkgs/development/tools/analysis/radare2/default.nix

1. it is the [upstream recommended way](http://rada.re/r/down.html)
2. http://cloud.radare.org (the tarball host) is currently down
3. there was [an incident](https://github.com/NixOS/nixpkgs/commit/938df03ed1ae250fd21a7615763b1ecabb041b66) with tarball rewrite 
4. ease to override the derivation to build the bleeding edge version from the github head.
on non-NixOS)
---

radare2: 1.4.0 -> 1.6.0

---

nixos/modules/services/web-servers/varnish/default.nix
pkgs/servers/varnish/digest.nix
pkgs/servers/varnish/geoip.nix
pkgs/servers/varnish/modules.nix
pkgs/servers/varnish/rtstatus.nix
pkgs/top-level/all-packages.nix

* nixos/varnish: command line compatible with varnish 5.2.1, fixes
https://github.com/NixOS/nixpkgs/issues/27409
* nixos/varnish: add support for modules (services.varnish.extraModules)
* varnish-modules: init at 0.10.2
* varnish-geoip: init at 1.0.2
* varnish-rtstatus: init at 1.2.0
* varnish-digest: init at 1.0.1
* added services.varnish.extraCommandLine option
it is https://github.com/NixOS/nixpkgs/pull/27413 squashed in another branch
on non-NixOS)
---

nixos/varnish: made compatible with varnish 5.1.2, add modules

---

nixos/modules/system/boot/kernel.nix

dedup and sort boot.kernelParams  to avoid restarting services on eval order change
Fixes https://github.com/NixOS/nixpkgs/issues/28277

boot.kernelParams: dedup and sort

---

pkgs/applications/window-managers/icewm/default.nix

Minor update
Please check what applies. Note that these are not hard requirements but merely serve as information for reviewers.
on non-NixOS)
---

icewm: 1.3.12 -> 1.4.2

---

nixos/modules/hardware/raid/hpsa.nix
nixos/modules/module-list.nix

To install NixOS on HP Proliant
```hpssacli``` is a maintenance utility to be used in ```boot.postBootCommands``` to configure cache params etc. I am not sure if it deserves its own place in ```all-packages.nix``` because it requires the hardware and two kernel modules to run.

nixos/hardware/raid/hpsa: init at 2.40

---

pkgs/build-support/setup-hooks/set-source-date-epoch-to-latest.sh

set-source-date-epoch-to-latest.sh to ignore files newer than ```$NIX_BUILD_TOP/..``` (unlike ```$NIX_BUILD_TOP``` it is root-owned and cannot be touched by ```nixbld1```).
Fixes https://github.com/NixOS/nixpkgs/issues/28218
mass-rebuild

[staging] set-source-date-epoch-to-latest.sh: ignore generated files

---

nixos/modules/services/networking/tinc.nix

Add "restartTriggers" back to restart the Tinc daemon when its peer is removed.
Reverted #27660
Discussed 
here: https://github.com/NixOS/nixpkgs/pull/27660#issuecomment-321415123
cc @fpletz

nixos/tinc: add "restartTriggers" back

---

pkgs/servers/mqtt/mosquitto/default.nix

On Darwin ```mosquitto``` is a CMake-project, so ```preBuild```'s current directory is ```build/``` where ```substituteInPlace``` cannot not find ```config.mk```

mosquitto: fix darwin build

---

pkgs/servers/sql/postgresql/timescaledb/default.nix
pkgs/top-level/all-packages.nix

PostgreSQL extension for time-series data
Requires PostgreSQL 9.6.x
To enable on NixOS:
```
config.services.postgresql = {
extraPlugins = [ pkgs.timescaledb ];
extraConfig = "shared_preload_libraries = 'timescaledb'";
}
```

timescaledb: init at 0.5.0

---

pkgs/data/fonts/nerdfonts/default.nix

Fixes #29928
The derivations depends on ``withFont``` parameter and thus it is not fixed output

nerdfonts: derivation is not fixed output

---

pkgs/applications/networking/p2p/vuze/default.nix
pkgs/top-level/all-packages.nix

A torrent client (build from Java sources)
---

vuze: init at 5750

---

pkgs/applications/networking/p2p/tixati/default.nix
pkgs/top-level/all-packages.nix

A torrent client (closed source single binary)
---

tixati: init at 2.55

---

pkgs/development/compilers/oraclejdk/jdk8cpu-linux.nix
pkgs/development/compilers/oraclejdk/jdk8psu-linux.nix

fix armv7l hashes, they was not updated with version bump https://github.com/nixos/nixpkgs/commit/08075d57e853a6b6ba71e64d4da5295e1c6aed4f

oraclejdk8: fix armv7l hashes

---

pkgs/development/tools/electron/default.nix

electron: 1.7.5 -> 1.8.1

---

pkgs/development/tools/coursier/default.nix

minor version bump, required for https://github.com/NixOS/nixpkgs/pull/32442#issuecomment-350334285

coursier: 1.0.0-RC3 -> 1.0.0-RC13

---

pkgs/applications/virtualization/virt-viewer/default.nix
pkgs/development/libraries/libvirt-glib/default.nix
pkgs/development/libraries/libvirt/default.nix

```libvirt``` works on ```aarch64-linux``` if compiled without ```xen```

libvirt: remove xen dependency on aarch64

---

pkgs/applications/virtualization/qemu/default.nix

New version.
CVE patches are included
---

qemu: 2.10.1 -> 2.11.0

---

nixos/modules/system/boot/initrd-ssh.nix

```dropbear``` has ```-R``` command line switch to generate hostkeys on demand, so the hostkey absence is not a fatal error
Fixes #24399
Fixes #24727

nixos/initrd-ssh: generate hostkeys if absent

---

pkgs/applications/virtualization/qemu/default.nix

* $out/bin/qemu-kvm should point to qemu-system-aarch64 on aarch64, ```libvirt``` expects it
* makeWrapper codes are separated as some architectures might require additional command flags (https://github.com/NixOS/nixpkgs/issues/31606#issuecomment-349675127)
* x86_64-on-i686 is not a native emulation and not supported by KVM, so it is removed from the list
@dezgeg

qemu: fix bin/qemu-kvm on aarch64 + minor fixes

---

pkgs/applications/networking/mailreaders/nylas-mail-bin/default.nix
pkgs/servers/monitoring/grafana/default.nix

```s3-us-west-2.amazonaws.com``` is not a worldwide available domain.
In particular, it is blocked in Russia:
```
--2017-12-19 23:15:33--  http://s3-us-west-2.amazonaws.com/
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 54.231.184.176
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|54.231.184.176|:80... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: http://forbidden.yota.ru/ [following]
--2017-12-19 23:15:33--  http://forbidden.yota.ru/
```

s3-us-west-2.amazonaws.com -> s3.amazonaws.com

---

pkgs/data/fonts/dejavu-fonts/default.nix

to make hash of fixed-output derivation independent on non-standard $NIX_STORE_DIR
Fixes https://github.com/NixOS/nixpkgs/issues/32909

dejavu_fonts: make relative symlink

---

pkgs/development/libraries/protobuf/2.5.nix
pkgs/top-level/all-packages.nix

Old ```protobuf``` versions were removed in https://github.com/NixOS/nixpkgs/pull/29134
Although ```protobuf-2.5.0``` is so legendary a version that some software (mostly from the Java world, for example, Hadoop, even the recent hadoop-3.0.0) needs exactly ```protobuf-2.5.0``` and not a newer version.
@abbradar

protobuf: restore version 2.5.0

---

nixos/modules/rename.nix
nixos/modules/virtualisation/libvirtd.nix
pkgs/development/libraries/libvirt/default.nix

Currently ```libvirt``` requires two ```qemu``` derivations:
```qemu``` and ```qemu_kvm``` which is just a truncated version  of ```qemu``` (defined as ```qemu.override { hostCpuOnly = true; }```).
This patch exposes an option ```virtualisation.libvirtd.qemuPackage``` which allows to choose which package to use: 
* ```pkgs.qemu_kvm``` if all your guests have the same CPU as host, or 
* ```pkgs.qemu``` which allows to emulate alien architectures (for example ```ARMV7L``` on ```X86_64```), or
* a custom derivation
```virtualisation.libvirtd.enableKVM``` option is vague and could be deprecate in favor of ```virtualisation.libvirtd.qemuPackage```, anyway it does allow to enable/disable kvm.

nixos/libvirt: avoid dependency on two qemu packages

---

nixos/modules/virtualisation/libvirtd.nix

...because daemon's $PATH does not include "/run/current-system/sw/bin"
Fixes #34048 
Fixes #33246

nixos/libvirtd: add qemu-img to $PATH of the daemon

---

pkgs/applications/networking/remote/xrdp/default.nix

minor version bump (security)
---

xrdp: 0.9.3 -> 0.9.5 [CVE-2017-16927]

---

pkgs/tools/graphics/pngquant/default.nix

pngquant: 2.9.1 -> 2.11.7

---

nixos/modules/services/web-servers/varnish/default.nix

check .vcl syntax at compile time (e.g. before nixops deployment)
---

nixos/varnish: check .vcl syntax at compile time

---

nixos/modules/programs/chromium.nix

remove unicode char '↪' in nix file, apparently copy-pasted there from the gutter of the editor window

nixos/programs.chromium: remove unicode char '↪'

---

nixos/modules/misc/label.nix

```Welcome to NixOS -18.03``` on agetty prompt looks weird
@oxij

nixos/label: no prepend '-' if there are no tags

---

pkgs/development/libraries/geoip/default.nix

Fix https://github.com/nixos/nixpkgs/commit/dfdb17d10d440e5ae704fcca7093d223730ec527 regression 
As geoip now is compiled from github instead of pre-./configure-d source tarball, there are no ```Makefile.in``` files yet on ```postPatch``` phase
@fpletz

geoip: fix regression

---

pkgs/development/libraries/libtoxcore/default.nix

$out/bin/tox-bootstrapd is not built without it, silently

libtoxcore: add libconfig to buildInputs

---

pkgs/applications/version-management/mercurial/default.nix
pkgs/applications/version-management/tortoisehg/default.nix

minor version bump
maybe mass rebuild (at least the packages using ```fetchhg```)
---

mercurial: 4.3.2 -> 4.5

---

nixos/modules/services/networking/tox-bootstrapd.nix

The daemon has new command line format

nixos/tox-bootstrapd: new command line format

---

pkgs/top-level/ocaml-packages.nix

No need to downgrade to ncurses5 after @dezgeg fix https://github.com/NixOS/nixpkgs/commit/8afcfb2bb6681c56ecf21e056d91d6748d953997

ocamlPackages.curses: use default ncurses

---

nixos/modules/programs/chromium.nix

[Policy configuration files live under /etc/chromium for Chromium, and under /etc/opt/chrome for Google Chrome.
](https://www.chromium.org/administrators/linux-quick-start)
Fixes https://github.com/NixOS/nixpkgs/issues/26889

nixos/programs.chromium: write policies for google-chrome too

---

pkgs/top-level/all-packages.nix

openjdk is [only for](https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/development/compilers/openjdk/8.nix#L19) ```x86_64-linux``` and ```i686-linux```
So let ```jdk``` and ```jre``` point to Oracle's on ```aarch64-linux``` as it is already done for ```armv7v-linux``` in https://github.com/NixOS/nixpkgs/pull/27419

jdk: use oraclejdk on aarch64

---

pkgs/development/tools/coursier/default.nix

minor update.
There is ```1.0.2``` already, but it does not work for me (fails with ```Exception in thread "main" java.lang.BootstrapMethodError: call site initialization exception```)

coursier: 1.0.0 -> 1.0.1

---

pkgs/development/compilers/graalvm/default.nix
pkgs/top-level/all-packages.nix

Ahead-Of-Time compiler for Java and JVM languages used [in production at Twitter allowing them to  slightly reduce the number of the servers](https://twitter.com/wirthi/status/928265955976843264)
---
Here is the open source version from https://github.com/oracle/graal, not [the binary bundle from oracle.com](http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html) 
It does not include [dynamic languages](https://github.com/oracle/graal/blob/f310d754b28cd117ea2a3014c01a7e8351921360/truffle/docs/Languages.md) (which are separate projects included in that binary bundle) and the closed-source enterprise components.
Fixes https://github.com/NixOS/nixpkgs/issues/34187
---

graalvm8: init at 0.31

---

pkgs/applications/networking/browsers/chromium/default.nix
pkgs/applications/networking/browsers/google-chrome/default.nix

https://github.com/NixOS/nixpkgs/pull/21679 did not escape special chars properly, so it was not possible to write something like
```
commandLineArgs = ''$([ `whoami` == "root" ] && echo "--no-sandbox") --user-data-dir=$HOME/.config/chromium'';
```
@7c6f434c

chromium, google-chrome: fix escaping of commandLineArgs

---

pkgs/applications/networking/p2p/frostwire/default.nix
pkgs/applications/networking/p2p/frostwire/frostwire-bin.nix
pkgs/top-level/all-packages.nix

1. version update
2. build from sources
3. fixed hardcoded "/usr/bin/mplayer" in the sources
4. the first example in nixpkgs how to do a gradle build
---

frostwire: 6.4.5 -> 6.6.3-build-253

---

pkgs/applications/editors/kodestudio/default.nix
pkgs/applications/graphics/pencil/default.nix
pkgs/applications/graphics/solvespace/default.nix
pkgs/applications/misc/deco/default.nix
pkgs/applications/misc/playonlinux/default.nix
pkgs/applications/networking/browsers/palemoon/default.nix
pkgs/applications/networking/dropbox/default.nix
pkgs/applications/networking/instant-messengers/ring-daemon/default.nix
pkgs/applications/networking/instant-messengers/signal-desktop/beta.nix
pkgs/applications/networking/instant-messengers/signal-desktop/default.nix
pkgs/applications/networking/remote/citrix-receiver/default.nix
pkgs/applications/networking/remote/teamviewer/default.nix
pkgs/applications/office/mendeley/default.nix
pkgs/applications/office/zotero/default.nix
pkgs/applications/science/logic/mcrl2/default.nix
pkgs/applications/science/math/scilab-bin/default.nix
pkgs/applications/window-managers/wtftw/default.nix
pkgs/development/libraries/AntTweakBar/default.nix
pkgs/development/libraries/kde-frameworks/kdelibs4support/default.nix
pkgs/development/libraries/pipewire/default.nix
pkgs/development/libraries/qt-5/modules/qtbase.nix
pkgs/development/libraries/qt-5/modules/qtwebengine.nix
pkgs/development/libraries/webkitgtk/2.18.nix
pkgs/development/ruby-modules/gem-config/default.nix
pkgs/development/web/postman/default.nix
pkgs/games/steam/chrootenv.nix
pkgs/games/steam/runtime-wrapped.nix
pkgs/tools/misc/x11idle/default.nix
pkgs/tools/typesetting/pdf2htmlEX/default.nix
pkgs/top-level/all-packages.nix

part of cleaning up from using aliases' old names
```xlibs``` was renamed to ```xorg``` in 2015 and still popping up

treewide: s/xlibs/xorg/g

---

pkgs/misc/emulators/wine/base.nix

treewide: s/saneBackends/sane-backends/g

---

pkgs/development/compilers/graalvm/default.nix

It does not fix anything, just reduce binary diff between ```oraclejdk8``` and derivatives ```jvmci8``` and ```graalvm8```
It breaks the mystical magic which allowed processing3 to work on graalvm8 only
https://github.com/NixOS/nixpkgs/pull/35643#issuecomment-372184272
@dtzWill

graalvm8: dontFixup = true

---

pkgs/tools/package-management/rpm/default.nix

Required to unpack .rpm files from intel.com: https://bugzilla.redhat.com/show_bug.cgi?id=1514190
Fixes #31557 (```intel-ocl``` )

rpm: 4.14.0 -> 4.14.1

---

pkgs/tools/networking/xnbd/default.nix
pkgs/top-level/all-packages.nix

It requires to mount network volumes on scaleway.com (including /-volume on baremetal servers, when ```xnbd-client``` is to be copied to initrd and [run in](https://github.com/scaleway/initrd/blob/51c564e6ac76c3be70622e6c92c6415732e063ec/Linux/tree-common/functions#L264) ```boot.initrd.preLVMCommands```).
Normal ```nbd``` does not work on scaleway (it shows errors about protocol mismatch).
Here are two commits "xnbd: init at 0.3.0" and "xnbd: 0.3.0 -> 0.4.0" to preserve working 0.3.0 derivation in the git history
The distros officially supported by scaleway.com (Ubuntu, etc) still use 0.3.0, so in case of possible issues with 0.4.0, the latter commit could be undone

xnbd: init at 0.4.0

---

nixos/modules/services/web-servers/varnish/default.nix
pkgs/servers/varnish/default.nix
pkgs/servers/varnish/digest.nix
pkgs/servers/varnish/dynamic.nix
pkgs/servers/varnish/geoip.nix
pkgs/servers/varnish/modules.nix
pkgs/servers/varnish/packages.nix
pkgs/servers/varnish/rtstatus.nix
pkgs/top-level/all-packages.nix

added ```Varnish 6``` (new version) and ```Varnish 4``` (legacy version still supported by upstream) in additional to ```Varnish 5```.

varnish4: init at 4.1.9; varnish6: init at 6.0.0

---

pkgs/development/libraries/libguestfs/appliance.nix
pkgs/development/libraries/libguestfs/default.nix
pkgs/top-level/all-packages.nix

1. Fixes #37540 (path to appliance)
2. Added possibility to build ```libguestfs``` without appliance to reduce closure size, as the default appliance is about 4GB (it can be passed in runtime ```$LIBGUESTFS_PATH```)
3. added ```installCheckPhase```
---

libguestfs: fix path to appliance

---

pkgs/applications/misc/mucommander/default.nix
pkgs/top-level/all-packages.nix

Cross-platform file manager (like Total Commander)
---

mucommander: init at 0.9.2

---

nixos/modules/installer/cd-dvd/system-tarball-fuloong2f.nix
nixos/modules/profiles/base.nix

replace deprecated alias s/mssys/ms-sys/g

treewide: replace deprecated alias s/mssys/ms-sys/g

---

pkgs/data/fonts/babelstone-han/default.nix

new font version; old link answers with 404

babelstone-han: 10.0.2 -> 11.0.0

---

nixos/modules/tasks/network-interfaces-scripted.nix

Print the failed command and the error message instead of just ```"failed"```

nixos/network-scripted: print error details

---

maintainers/maintainer-list.nix
nixos/modules/module-list.nix
nixos/modules/services/misc/safeeyes.nix
pkgs/applications/misc/safeeyes/default.nix
pkgs/top-level/all-packages.nix

---
1. 
```
ERROR:root:Error in loading the plugin: notification
```
2. 
```
(safeeyes:2448): Gtk-WARNING **: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
```
adding `"--prefix XDG_DATA_DIRS : \"${gnome3.defaultIconTheme}/share:$GSETTINGS_SCHEMAS_PATH\""` to `makeWrapperArgs` didnt help

safeeyes: init at 2.0.2

---

nixos/modules/tasks/filesystems/exfat.nix

```exfat-utils``` and ```fuse_exfat``` are both aliases of ```exfat```

exfat-utils, fuse_exfat -> exfat

---

pkgs/tools/security/scallion/default.nix
pkgs/top-level/all-packages.nix

A GPU-based tor hidden service name generator
We have  ```eschalot``` here, which is CPU-only
---

scallion: init at 2.1

---

pkgs/development/node-packages/default-v6.nix

https://github.com/NixOS/nixpkgs/issues/38946
---

node2nix: add nix as dependency (fix for #38946)

---

pkgs/data/fonts/babelstone-han/default.nix

new font version; old link answers with 404

babelstone-han: 11.0.0 -> 11.0.2

---

pkgs/applications/networking/p2p/tixati/default.nix

Minor version bump.
@ryantm For unknown reason repology [does not see](https://repology.org/metapackage/tixati/versions) the presence of this package in nixpkgs; this results in your bot skipping it. There could be more packages like this one
---

tixati: 2.55 -> 2.57

---

pkgs/development/compilers/go/1.10.nix
pkgs/development/compilers/go/1.9.nix

On a NixOS laptop ```TestWritevError``` sometimes hangs (#37704) and ```TestVariousDeadlines``` fails with
```
--- FAIL: TestVariousDeadlines (5.00s)
timeout_test.go:878: 1ns run 1/1
timeout_test.go:903: for 1ns run 1/1, good client timeout after 19.113µs, reading 0 bytes
timeout_test.go:913: for 1ns run 1/1, server in 794.51µs wrote 393216: readfrom tcp4 127.0.0.1:43227->127.0.0.1:44660: write tcp4 127.0.0.1:43227->127.0.0.1:44660: write: connection reset by peer
timeout_test.go:878: 2ns run 1/1
timeout_test.go:903: for 2ns run 1/1, good client timeout after 4.91µs, reading 0 bytes
timeout_test.go:917: for 2ns run 1/1, timeout waiting for server to finish writing
FAIL
FAIL    net     6.498s
```
So they are added to the list of problematic tests which do not run.
Fixes #37704

 go_1_{9,10}: disable problematic tests in net module

---

pkgs/development/compilers/graalvm/default.nix

Minor update and fix the build which is broken since the default GCC hardening was changed
---

graalvm8: 0.31 -> 1.0.0-rc1

---

pkgs/applications/networking/p2p/frostwire/default.nix
pkgs/applications/networking/p2p/frostwire/frostwire-bin.nix

 frostwire: 6.6.3 -> 6.6.7

---

lib/default.nix
lib/tests/misc.nix
lib/trivial.nix

Add ```bitAnd```, ```bitOr```, ```bitXor``` recently introduced to Nix as builtins (https://github.com/NixOS/nix/pull/2157) with fallback version for old versions of Nix
Example use case https://github.com/NixOS/nixpkgs/issues/41251#issuecomment-393664755

lib: bitAnd, bitOr, bitXor

---

pkgs/tools/backup/znapzend/default.nix

fix build by pinning old versions of Perl Libraries
fixes https://github.com/NixOS/nixpkgs/issues/40516
cc @Infinisil: please test, I have not ```zfs``` here, so I checked only that it runs

znapzend: fix build

---

pkgs/top-level/perl-packages.nix

These modules have been included into other packages and do not have own packages anymore:
https://metacpan.org/pod/Dist::Zilla::Plugin::NoTabsTests
https://metacpan.org/pod/Email::MIME::Modifier
https://metacpan.org/pod/ExtUtils::Command
https://metacpan.org/pod/Parse::CPAN::Meta
https://metacpan.org/pod/Test::Tester
https://metacpan.org/pod/Test::use::ok
@rycee

[staging] perlPackages: convert some modules to aliases

---

pkgs/development/python-modules/Cython/default.nix

Follow up #41453 "python36Packages.cython: Disable tests on aarch64"
some tests are failing on ```i686-linux```

python27Packages.cython, python36Packages.cython: Disable tests on i686

---

nixos/modules/services/networking/sslh.nix

nixos/sslh: support transparent proxying

---

nixos/modules/services/networking/nat.nix

```networking.nat.externalInterface``` is not required in the simple cases
Moreover, ```networking.nat.externalInterface``` is not always known at the configuration time
for example, on a laptop (which might provide nat for the virtual machines or hosapd-connected devices) ```externalInterface``` flips between ```eth0``` and ```wlan0``` depending on whether WiFi or Ethernet cable are connected

nixos/nat: optional networking.nat.externalInterface

---

lib/default.nix
lib/lists.nix

Add ```groupBy``` function inspired by Scala lib
Basically it just a ```partiton``` function which is not limited to 2 groups
(```partition``` could be simplified to ```partition = pred: groupBy (x: if pred x then "right" else "wrong")```)
Example use case #37690: generating bash case-expression without duplicates

lib: add groupBy

---

pkgs/top-level/perl-packages.nix

Fixes cross-compilation https://github.com/NixOS/nixpkgs/pull/41712#issuecomment-396128046
it is a reimplementation of https://github.com/NixOS/nixpkgs/commit/b0d6c67505e1 from https://github.com/NixOS/nixpkgs/pull/36187 compatible with newer version of ```perlPackages.JSON```
@ElvishJerricco

perlPackages.JSON: fix cross-compilation

---

nixos/modules/system/boot/initrd-network.nix

Default router on Hetzner Cloud is ```172.31.1.1``` 
So ```ip route add default via "172.31.1.1" dev "eth0"``` fails because the router address is not reachable.

nixos/initrd-network: support hetzner

---

nixos/modules/services/networking/unbound.nix

```unbound``` sometimes fails to start (exits with code 1) on the first run but starts well on the second run
but ```systemd``` service did not try to restart it.

nixos/unbound: add restart

---

nixos/modules/services/networking/tinc.nix

I did it once (https://github.com/NixOS/nixpkgs/pull/27660) and then put back (https://github.com/NixOS/nixpkgs/pull/29881) with the only reason to force restart ```tinc``` if some of the peers has been removed from the configuration in order ```tinc``` to forget its public key as soon as possible (as the peer removal might occur because of its key has been compromised, a laptop has been stolen, a server hacked, etc; so quicker key removal would prevent connecting to VPN using that key).
But since ```tinc``` distribute public keys in a gossip way, restarting ```tinc``` does not help to forget deprecated keys, so now it is just a needless restart condition and redundant code.
It fixes
```# tinc.lan export```
```Could not open /etc/tinc/tinc.conf: No such file or directory```

nixos/tinc: minor fixes

---

nixos/modules/services/networking/xrdp.nix

```services.xserver.enable = true``` enables it, but ```xrdp``` might be used with ```services.xserver.enable = false``` too

nixos/xrdp: add fonts.enableDefaultFonts

---

pkgs/development/interpreters/perl/default.nix
pkgs/top-level/all-packages.nix

new version added.
default ```perl``` is still ```5.24.x```

perl528: init at 5.28.0

---

pkgs/top-level/perl-packages.nix

fix build problem
```
builder for '/nix/store/dkj8rc5zrh2x8scl1q9ra44x7b0k6z0v-perl-MHonArc-2.6.18.drv' failed to produce output path '/nix/store/kjyzhqxlnsv6vmfrygr7c472zhrlbdnr-perl-MHonArc-2.6.18-devdoc' 
```

perlPackages.MHonArc: fix build

---

pkgs/top-level/perl-packages.nix

mark old and unmaintained by upstream packages as broken

perlPackages: add meta.broken = true;

---

pkgs/top-level/perl-packages.nix

Collect the aliases together and add possibility to disable them with ```config.skipAliases``` introduced in https://github.com/NixOS/nixpkgs/pull/39686
Small clean-up, no rebuild at all.
PR is against ```staging``` only to avoid merge conflicts because other massive changes in ```perl-packages.nix``` are going on in ```staging```

[staging] perl-packages.nix: collect aliases

---

pkgs/development/interpreters/perl/default.nix

Always expose ```perl.version``` 
Currently it is only visible ```if (stdenv.buildPlatform != stdenv.hostPlatform)```
As ```perl-5.26``` introduces some breaking changes it would allow to write conditions like
```optional (versionAtLeast perl.version "5.26")```

[staging] always expose perl.version

---

pkgs/development/tools/misc/automake/automake-1.11.x.nix
pkgs/development/tools/misc/automake/fix-perl-5.26.patch

Fix legacy ```automake``` to work with moderner ```perl```

[staging] automake111x: fix for perl5.26 ("Unescaped left brace in regex is illegal here")

---

pkgs/applications/networking/remote/xrdp/default.nix

minor update (fixed memory leaks, etc)

xrdp: 0.9.5 -> 0.9.7

---

pkgs/data/fonts/babelstone-han/default.nix

```11.0.2``` is not available anymore, new version is on the same download url.

fonts/babestone-han: 11.0.2 -> 11.0.3

---

lib/attrsets.nix
lib/lists.nix

prepare for ```concatMap``` and ```mapAttrs``` to be builtins
(to reduce Nix memory consumption when evaluating big ```nixpkgs```, PR https://github.com/NixOS/nix/pull/2273)

 lib: concatMap and mapAttrs to be builtins

---

nixos/modules/programs/digitalbitbox/default.nix
nixos/modules/services/logging/journalwatch.nix
nixos/modules/services/web-apps/matomo.nix
nixos/modules/services/web-apps/nexus.nix

```stdenv``` was not defined in the scope, so evaluation failed

nixos/digitalbitbox: fix evaluation

---

nixos/modules/i18n/input-method/default.nix

A function which enumerates options crashed on this ```default = null``` when ```null``` is not allowed by the type

options.i18n.inputMethod.package: fix type

---

pkgs/development/libraries/hspell/default.nix

fix build when default ```perl``` is 5.26+

hspell: fix build when default perl is 5.26+

---

pkgs/development/python-modules/Cython/default.nix

Attempt to fix the timeout (https://github.com/NixOS/nixpkgs/issues/41673#issuecomment-399775390)
There are too many tests and they run sequentially
@dotlambda

pythonPackages.cython: run tests in parallel

---

nixos/modules/rename.nix
nixos/modules/services/x11/desktop-managers/xfce.nix

remove option which is not read and thus has no effect

nixos: remove option services.xserver.desktopManager.xfce.screenLock

---

pkgs/desktops/xfce/panel-plugins/xfce4-hardware-monitor-plugin.nix

update within XFCE 4.12 (stable)
it does not bring GTK3 or any new dependencies
[CHANGELOG and sources diff](https://git.xfce.org/panel-plugins/xfce4-hardware-monitor-plugin/diff/?id=e68cd4972155057a5c575c7cc8a2b0f21bd94a62&id2=5ef872f4fb3d725fa45f8b60f869ad6f9336978f)
---

xfce.xfce4-hardware-monitor-plugin: 1.5.0 -> 1.6.0

---

pkgs/development/tools/build-managers/bazel/0.4.nix
pkgs/development/tools/build-managers/bazel/default.nix

```bazel``` cannot be built twice on the same machine because a build left ```/tmp/.bazel``` owned by one of ```nixbld*``` users and inaccessible for any other build user.
```TMPDIR=$(mktemp -d)``` and ```TMPDIR=$NIX_BUILD_TOP/tmp``` still hit "infinite symlink detector", 
Fixes https://github.com/NixOS/nixpkgs/issues/43500
Related: https://github.com/NixOS/nixpkgs/pull/23074
cc @izuk

bazel: use per-user tmp directory to avoid conflict with other builders

---

pkgs/development/libraries/pango/default.nix

new version, tests passed (at least on ```x86_64-linux```)

[staging] pango: 1.40.14 -> 1.42.1

---

pkgs/applications/version-management/git-and-tools/default.nix
pkgs/desktops/gnome-3/default.nix
pkgs/desktops/xfce/default.nix
pkgs/misc/vim-plugins/default.nix
pkgs/top-level/perl-packages.nix
pkgs/top-level/stage.nix

add possibility to disable aliases with ```config.skipAliases``` introduced in #39686
Small clean-up, no rebuild at all.
cc @matthewbauer

config.skipAliases: also disable vim, git, xfce and gnome3 aliases

---

pkgs/desktops/xfce4-13/xfce4-panel/default.nix

xfce4-13.xfce4-panel: 4.13.2 -> 4.13.3

---

pkgs/desktops/xfce/core/gtk-xfce-engine.nix

xfce.gtk-xfce-engine: fix build when withGtk3=true

---

pkgs/desktops/xfce4-13/xfce4-screenshooter/default.nix

xfce4-13.xfce4-screenshooter: 1.9.1 -> 1.9.2

---

pkgs/desktops/xfce4-13/ristretto/default.nix

ristretto: 0.8.2 -> 0.8.3

---

pkgs/desktops/xfce4-13/xfce4-terminal/default.nix

xfce4-terminal: 0.8.6 -> 0.8.7.4

---

pkgs/desktops/xfce4-13/xfce4-settings/default.nix

xfce4-settings: 4.13.1 -> 4.13.4

---

pkgs/development/libraries/libxklavier/default.nix

xfce 4.13 needs it
unfortunately, upstream has no source tarball, only git
---

libxklavier: 5.3 -> 5.4

---

pkgs/desktops/xfce4-13/xfce4-volumed-pulse/default.nix

minor update, upstream (XFCE 4.13) switched to ```gtk3``` 
---

xfce4-13.xfce4-volumed-pulse: 0.2.2 -> 0.2.3

---

pkgs/desktops/xfce4-13/xfconf/default.nix

xfconf: 4.13.4 -> 4.13.5

---

pkgs/desktops/xfce4-13/xfce4-notifyd/default.nix

xfce4-notifyd: 0.4.1 -> 0.4.2

---

pkgs/desktops/xfce4-13/libxfce4util/default.nix

xfce4-13.libxfce4util: 4.13.1 -> 4.13.2

---

pkgs/desktops/xfce4-13/xfwm4/default.nix

fix build (add libXdamage dependency)
---

xfce4-13.xfwm4: fix build (add libXdamage dependency)

---

pkgs/desktops/xfce4-13/xfce4-taskmanager/default.nix

xfce4-13.xfce4-taskmanager: 1.2.0 -> 1.2.1

---

pkgs/desktops/xfce4-13/xfce4-dict/default.nix

xfce4-13.xfce4-dict: 0.8.0 -> 0.8.1

---

pkgs/desktops/xfce4-13/parole/default.nix

xfce4-13.parole: 0.9.2 -> 1.0.1

---

pkgs/desktops/xfce4-13/default.nix
pkgs/desktops/xfce4-13/mousepad/default.nix

xfce4-13.mousepad: 0.4.0 -> 0.4.1

---

pkgs/stdenv/generic/setup.sh

From @Profpatsch's [comment](https://github.com/NixOS/nixpkgs/pull/35304#issuecomment-367723420): 
> It looks to me like there’s other funny business going on, like --subst-var silently coercing to "" if the variable does not exist.
As that PR is abandoned, this small feature needs its own PR

[staging] substitute(): --subst-var was silently coercing to "" if the variable does not exist.

---

pkgs/applications/editors/geany/default.nix
pkgs/applications/graphics/dia/default.nix
pkgs/applications/graphics/glabels/default.nix
pkgs/applications/graphics/inkscape/default.nix
pkgs/applications/networking/newsreaders/liferea/default.nix
pkgs/applications/networking/p2p/transmission/default.nix
pkgs/applications/office/gnucash/2.4.nix
pkgs/applications/office/gnucash/2.6.nix
pkgs/applications/video/handbrake/default.nix
pkgs/desktops/xfce/applications/orage.nix
pkgs/desktops/xfce/applications/xfce4-notifyd.nix
pkgs/desktops/xfce/core/thunar-build.nix
pkgs/desktops/xfce/core/thunar-volman.nix
pkgs/desktops/xfce/panel-plugins/xfce4-battery-plugin.nix
pkgs/desktops/xfce/panel-plugins/xfce4-clipman-plugin.nix
pkgs/desktops/xfce/panel-plugins/xfce4-cpufreq-plugin.nix
pkgs/desktops/xfce/panel-plugins/xfce4-cpugraph-plugin.nix
pkgs/desktops/xfce/panel-plugins/xfce4-netload-plugin.nix
pkgs/desktops/xfce/panel-plugins/xfce4-pulseaudio-plugin.nix
pkgs/desktops/xfce/panel-plugins/xfce4-weather-plugin.nix
pkgs/desktops/xfce/thunar-plugins/archive/default.nix
pkgs/desktops/xfce/thunar-plugins/dropbox/default.nix

There is (almost empty) ```hicolor-icon-theme``` package which does "rm $out/share/icons/hicolor/icon-theme.cache" and also collects icon paths into ```$XDG_ICON_DIRS```
I assume it is preferred to ad-hoc "rm $out/share/icons/hicolor/icon-theme.cache" in ```postInstall```
Related https://github.com/NixOS/nixpkgs/issues/39057 https://github.com/NixOS/nixpkgs/pull/43150
cc @jtojnar

"rm $out/share/icons/hicolor/icon-theme.cache" -> hicolor-icon-theme setup-hook

---

pkgs/desktops/xfce4-13/default.nix
pkgs/desktops/xfce4-13/mkXfceDerivation.nix
pkgs/desktops/xfce4-13/xfce4-battery-plugin/default.nix

A panel plugin which displays battery status.
```mkXfceDerivation```: altered to allow git revision be different from ```"${pname}-${version}"```
```mkXfceDerivation```: added ```hicolor-icon-theme``` hook as it is needed for almost all XFCE applications
cc @yegortimoshenko as author of ```mkXfceDerivation```
cc @vcunat as xfce maintainer
---

xfce4-13.xfce4-battery-plugin: init at 1.1.0

---

pkgs/desktops/xfce4-13/default.nix
pkgs/desktops/xfce4-13/xfce4-pulseaudio-plugin/default.nix

xfce4-13.xfce4-pulseaudio-plugin: init at 0.4.1

---

pkgs/desktops/xfce4-13/default.nix
pkgs/desktops/xfce4-13/xfce4-netload-plugin/default.nix

xfce4-13.xfce4-netload-plugin: init at 1.3.1

---

pkgs/desktops/xfce4-13/default.nix
pkgs/desktops/xfce4-13/xfce4-cpufreq-plugin/default.nix

xfce4-13.xfce4-cpufreq-plugin: init at 1.2.0

---

pkgs/desktops/xfce4-13/default.nix
pkgs/desktops/xfce4-13/xfce4-whiskermenu-plugin/default.nix

xfce4-13.xfce4-whiskermenu-plugin: init at 2.2.0

---

pkgs/desktops/xfce4-13/default.nix
pkgs/desktops/xfce4-13/xfce4-xkb-plugin/default.nix

xfce4-13.xfce4-xkb-plugin: init at 0.8.1

---

pkgs/desktops/xfce4-13/default.nix
pkgs/desktops/xfce4-13/xfce4-clipman-plugin/default.nix

xfce4-13.xfce4-clipman-plugin: init at 1.4.2

---

pkgs/desktops/xfce4-13/default.nix
pkgs/desktops/xfce4-13/xfce4-session/default.nix

xfce4-13.xfce4-session: init at 4.13.0

---

pkgs/desktops/xfce4-13/xfce4-panel/default.nix

This should be part of https://github.com/NixOS/nixpkgs/pull/43522
I did the fix for XFCE 4.12 (https://github.com/NixOS/nixpkgs/pull/43522/files#diff-d5900334ef3a7a897a90b8a3a9eac90c) but forgot for XFCE 4.13
---

xfce4-13.xfce4-panel: fix path to tzdata

---

pkgs/desktops/xfce/art/xfce4-icon-theme.nix
pkgs/desktops/xfce/panel-plugins/xfce4-embed-plugin.nix
pkgs/desktops/xfce4-13/default.nix
pkgs/desktops/xfce4-13/xfburn/default.nix
pkgs/desktops/xfce4-13/xfce4-mixer/default.nix

backport panel plugins and icon themes from xfce4-12
---

xfce4-13: backport panel plugins and icon themes from xfce4-12

---

pkgs/development/perl-modules/generic/default.nix
pkgs/top-level/all-packages.nix
pkgs/top-level/perl-packages.nix

```Perl 5.24``` [is deprecated upstream](https://www.cpan.org/src/README.html) so it might be gone in ```nixpkgs-18.09```
I have been using ```Perl 5.28``` as default NixOS Perl for about a month.
This PR includes https://github.com/NixOS/nixpkgs/pull/42659 as the first commit
---

perl: 5.24.4 -> 5.28.0

---

pkgs/development/perl-modules/generic/default.nix
pkgs/top-level/all-packages.nix
pkgs/top-level/perl-packages.nix

Although there were ```pkgs.perl522``` and ```pkgs.perl524``` and ```pkgs.perl526```,
```pkgs.perlPackages``` were build only for ```pkgs.perl524``` leaving other versions without packages
This PR introduces ```pkgs.perl522Packages```, ```pkgs.perl524Packages```, ```pkgs.perl526Packages```, ```pkgs.perl528Packages``` making Perl support much like those for Python, PHP, Ocaml, ...

[staging] perlPackages -> perl{522,524,526,528}Packages

---

pkgs/development/libraries/libvirt/default.nix
pkgs/development/python-modules/libvirt/default.nix
pkgs/top-level/perl-packages.nix

libvirt: 4.5.0 -> 4.6.0

---

pkgs/os-specific/linux/firmware/intel2200BGFirmware/default.nix

intel2200BGFirmware: fixed-output derivation

---

pkgs/os-specific/linux/hwdata/default.nix

hwdata: fixed-output derivation

---

pkgs/data/misc/iana-etc/default.nix

iana-etc: fixed output derivation

---

pkgs/os-specific/linux/firmware/firmware-linux-nonfree/default.nix

firmware-linux-nonfree: fixed-output derivation

---

pkgs/os-specific/linux/firmware/broadcom-bt-firmware/default.nix

broadcom-bt-firmware: fixed output derivation

---

pkgs/os-specific/linux/firmware/zd1211/default.nix

zd1211-firmware: fixed output derivation

---

pkgs/top-level/all-packages.nix

scallion does not work with ```mono5``` (which is the default now)

scallion: use mono4

---

pkgs/applications/graphics/processing3/default.nix

update and fix build because hash of ```http://download.processing.org/reference.zip``` has been changed
---

processing: 3.3.7 -> 3.4

---

pkgs/development/libraries/libvirt/default.nix

[libvirt-4.6.0 was built with no qemu support ](https://github.com/NixOS/nixpkgs/pull/44566#issuecomment-412222753)
@Izorkin 
---

libvirt: jansson required for qemu suppport

---

nixos/modules/services/misc/nix-daemon.nix

https://github.com/NixOS/nix/issues/1127#issuecomment-412176841
---

nixos/nix-daemon: build-max-jobs, add support to auto

---

nixos/modules/system/activation/top-level.nix

```$toplevel/system``` file to contain the name of the system where the closure to be run instead of the platform where the closure have been built
So it might me used in
```
qemu-system-$(cat $toplevel/system | sed 's/-linux$//') \
-kernel $toplevel/kernel \
-initrd $toplevel/initrd \
...
```
Fixes https://github.com/NixOS/nixpkgs/issues/45386

$toplevel/system: buildPlatform.system -> hostPlatform.system

---

pkgs/build-support/fetchpatch/default.nix

Fix  cross-compilation errors
```lsdiff: cannot execute binary file```
```filterdiff: cannot execute binary file```
I wonder how was (fully cross-compiled?) RiscV port possible without this fix
cc @Ericson2314

fetchpatch: patchutils -> buildPackages.patchutils

---

nixos/modules/installer/cd-dvd/iso-image.nix
nixos/modules/profiles/all-hardware.nix

Following up https://github.com/NixOS/nixpkgs/pull/23665
Bootable USB-drives are not limited to ISO-images, there can be "normal" MBR/GPT-partitioned disk connected via USB-rack.
Also, "uas" implies "usb-storage", so there is no need to mention both.

usb-storage -> uas

---

nixos/lib/qemu-flags.nix
nixos/tests/ec2.nix
pkgs/applications/virtualization/qemu/default.nix

do not merge, it is just to test the build on different platforms
I am not sure if it is a good idea to merge ```qemu-3.0.0-rc1```, but ```qemu-3.0.0``` may be ready by the time of ```nixos-18.09``` so the testing of ```3.0.0-rc1``` on ```nixos-unstable``` may have sense.

qemu: 2.12.1 -> 3.0.0

---

nixos/modules/system/boot/stage-1-init.sh

```fsck``` of a mounted filesystems fails with error code 8 "Operational error" and halts the boot processing
It is a rare problem on simple disk configurations, but there are weird cloud hostings with network-only disks (scaleway)  or ones which do not allow disk partitioning (most XEN clouds) forcing to put encrypted root filesystem into a file.
In those cases ```boot.initrd.preLVMCommand``` is something like 
```mkOrder 100 ''mkdir /boot ; mount /dev/xvda /boot''``` 
and the fs is already mounted at the ```fsck``` time 
----
A simpler solution is to change
https://github.com/NixOS/nixpkgs/blob/8fb33bcb2d6d573176702d0daecf59187df44e11/nixos/modules/system/boot/stage-1-init.sh#L311
to
```if test $fsckResult -ge 9; then ```
allowing to go on booting if ```fsck``` failed with error code 8, …

stage-1-init.sh: do not check mounted filesystems

---

nixos/modules/services/x11/display-managers/default.nix

It fixes the following issue:
Adding programs to a WM session, for example the programs to run in tray area:
```
services.xserver.windowManager.session = [{
name = "icewm";
start = ''
${pkgs.icewm}/bin/icewmbg &
${pkgs.yubioath-desktop}/bin/yubioath-gui -t &  # TOTP passwords
${pkgs.pasystray}/bin/pasystray &               # Volume control
'';
}];
```
results in duplicated cases in ```xsession```
```bash
export windowManager="icewm"
case "$windowManager" in
(icewm)
.../bin/icewmbg &
.../yubioath-gui -t &
.../pasystray &
;;
(none)
...
;;
(icewm)
.../bin/icewm &
waitPID=$!
;;
(*) echo "$0: Window manager '$windowManager' not found.";;
esac
```
which obviously does not work because there are two ```(icewm)``` cases

nixos/xserver.windowManager.session: handle duplicate names

---

nixos/modules/system/boot/loader/grub/install-grub.pl

Although double ```/``` in paths is not a problem for the GRUB supplied with nixpkgs (it interprets ```//``` as ```/```), sometimes NixOS's ```grub.conf``` read by external GRUB and there are versions of GRUB which fail parsing config like this:

install-grub.pl: avoid double '/' in menu.lst and grub.conf

---

pkgs/top-level/perl-packages.nix

perlPackages.UNIVERSALref: broken with perl 5.26+

---

pkgs/development/libraries/libguestfs/appliance.nix

Hydra fails with "Output limit exceeded"
https://hydra.nixos.org/build/80720522
ZHF #45960

libguestfs-appliance: do not build on Hydra

---

pkgs/top-level/perl-packages.nix

perlPackages.TestAggregate: broken with perl 5.26+

---

pkgs/top-level/perl-packages.nix

ZHF 18.09 https://github.com/NixOS/nixpkgs/issues/45960
* ```perlXXXPackages.MojoIOLoopForkCall``` fixed by undoing https://github.com/NixOS/nixpkgs/commit/471b3f1dec0a077748083d181660c0c6ddd21086 (not sure if we have do this)
* ```perlXXXPackages.Connector``` tests fail in sandbox, got passed without sandbox
* ```perl528Packages.MojoIOLoopForkCall``` failed with `-Werror=format-security`, hardening disabled

perlPackages: ZHF 18.09

---

pkgs/development/interpreters/perl/default.nix
pkgs/top-level/all-packages.nix

The idea is to build ```perlPackages``` also against the bleeding edge ```perl``` and to see failures and to fix them before the next ```perl``` release.
It should not cause any rebuild

perl: add devel version at 5.29.3

---

pkgs/top-level/all-packages.nix

I cannot reproduce the bug https://sourceforge.net/p/net-snmp/bugs/2712/ and able to build net_snmp with default perl (which is 5.28)
Let's see what ofborg says. If it fails, there is either an option to upgrade ```net_snmp``` to 5.8 or a  [patch](https://github.com/FreeSNMP/net-snmp/commit/4e793461e96a2b4fd81142ab312d074d5c8841fa.patch) to fix the bug in ```net_snmp``` 5.7.3 LTS
The goal is to deprecate perl-5.22 and perl-5.24, it is the last reference

net_snmp: build with default perl

---

pkgs/development/interpreters/perl/default.nix
pkgs/top-level/all-packages.nix

remove obsolete Perl versions
@xeji

remove Perl 5.22 and 5.24 (end-of-life upstream few months ago)

---

pkgs/top-level/perl-packages.nix

cpan2nix updates
mostly cleanup, as the oldest supported version is now ```5.26``` which includes some of the packages

cpan2nix updates

---

pkgs/development/interpreters/perl/default.nix

One more fruitless version comparison forgotten in #47801

remove support for pre-5.26 Perl (2)

---

nixos/modules/system/boot/initrd-network.nix

* acquire DHCP on the interfaces with ```networking.interface.$name.useDHCP == true``` or on all interfaces if ```networking.useDHCP == true``` (was only "eth0", it is ```udhcpc```'s default behaviour)
* respect ```mtu``` if it was in DHCP answer (it happens in the wild, on some hostings)
* acquire and set up ```staticroutes``` (unlike others clients, ```udhcpc``` does not do the query by default); this supersedes https://github.com/NixOS/nixpkgs/pull/41829
Shortly, it makes ```initrd-network``` closer to network in stage-2
It fixes the practical cases where ```initrd-network``` has problems while stage-2 works well.

nixos/initrd-network: multiple DHCP fixes

---

pkgs/tools/misc/screen/default.nix

fix cross-compiling with awful hack taken from samba
https://github.com/NixOS/nixpkgs/blob/fce8f26af6ef8209c7d282938e9457438746841b/pkgs/servers/samba/3.x.nix

screen: fix cross-compiling

---

pkgs/development/interpreters/perl/default.nix

To support perl 5.29
https://github.com/arsv/perl-cross/compare/1.2...master

perl-cross: 1.2 -> gitmaster

---

nixos/modules/system/boot/stage-1.nix

use ```bash``` and ```busybox``` from ```buildPackages``` to check syntax at build time

bootStage1: fix cross build

---

nixos/modules/config/system-path.nix
nixos/modules/config/xdg/mime.nix
nixos/modules/misc/documentation.nix

use ```buildPackages``` in ```environment.extraSetup```, it is build time code

use buildPackages in environment.extraSetup

---

nixos/modules/virtualisation/qemu-guest-agent.nix

there is no top-level ```pkgs.kvm```

nixos/qemu-guest-agent: pkgs.{kvm -> qemu}

---

pkgs/servers/varnish/default.nix

version bump as @r-ryantm fails to update (https://gist.githubusercontent.com/ryantm/0b203cc115c9e557e5df7605d8b1d28d/raw)

varnish4: 4.1.9 -> 4.1.10

---

pkgs/servers/varnish/default.nix

version bump as @r-ryantm fails to update (https://gist.githubusercontent.com/ryantm/0b203cc115c9e557e5df7605d8b1d28d/raw)

varnish6: 6.0.1 -> 6.1.0

---

pkgs/applications/networking/browsers/chromium/plugins.nix

to prevent their installation on aarch64

chromium plugins: add meta.platforms

---

pkgs/development/compilers/oraclejdk/jdk8cpu-linux.nix
pkgs/development/compilers/oraclejdk/jdk8psu-linux.nix

old files are not available on the upstream website

oraclejdk8: 8u181 -> 8u191

---

pkgs/applications/networking/browsers/chromium/common.nix

Chromium 71+ depends on ```at-spi2-core```
This alone does not fix the build.
There are few patches needed, but they are already upstream, so minor bump will likely fix the build

chromium 71+: add at-spi2-core dependency

---

pkgs/applications/networking/browsers/chromium/common.nix

This option removed upstream
As warnings are set to be fatal, it breaks the build

chromium 70+: there is no more option 'use_gtk3'

---

pkgs/applications/networking/browsers/chromium/default.nix

Propagate ```stdenv``` to ```chromium``` scope to allow using another C++ compiler.
It seems that ```chromium```'s developers are using GCC8 and often write code with too modern features which GCC7 does not understand, then in a month or two backport the fixes which we have to cherry-pick 
_(examples which currently need to add to chromium derivation in order to fix ```chromiumDev``` build: https://github.com/chromium/chromium/commit/cbdb8bd6567c8143dc8c1e5e86a21a8ea064eea4 https://github.com/chromium/chromium/commit/c9580757cfd9f7fd73e3f6d71e8a31a18b7e2dd5 https://github.com/chromium/chromium/commit/7c9af6c257d681159b8764c8d3d7b70f1d2f7d3a)_
So switching to ```GCC8``` is desirable, at least for ```chromiumDev``` and ```chromiumCanary```.
This PR just makes it possible to override the …

chromium: propagate stdenv for "chromium.override{ stdenv=gcc8Stdenv; }"

---

pkgs/tools/security/nmap/default.nix

fix cross-build by adding target prefixes and hinting ```configure``` where to locate ```liblua``` files

[ok] nmap: fix cross-build

---

pkgs/top-level/perl-packages.nix

minor cleanup
The removed identifiers are either set to ```null``` or duplicated in aliases section on the bottom of the file:
https://github.com/NixOS/nixpkgs/blob/bc9bd012c4ba75df94a688b281369a1b433d1264/pkgs/top-level/perl-packages.nix#L17870-L17940

perlPackages: fix evaluate with allowAliases=false

---

nixos/modules/virtualisation/amazon-image.nix

based on https://www.ec2instances.info/
---

amazon-image: fix typo in comment

---

nixos/modules/services/misc/nix-daemon.nix

the check always fails because of architecture mismatch

nixos/nix: ignore nix.checkConfig when cross-compiling

---

pkgs/tools/text/gnused/422.nix
pkgs/tools/text/gnused/default.nix
pkgs/top-level/all-packages.nix

make ```sed``` working on Windows
---

gnused: fix Windows build

---

pkgs/applications/misc/far2l/default.nix

There is a bug on Darwin preverning ```far2l``` to run when ```argv[0]``` is not the full path to the executable but a relative path or something like ```/run/current-system/sw/bin/far2l```
https://github.com/elfmz/far2l/issues/416#issuecomment-436742723
---

far2l: fix Darwin bug

---

pkgs/shells/bash/4.4.nix

bash: fix typo in configureFlags

---

pkgs/top-level/all-packages.nix

```fetchgit``` is to use ```buildPackages```'s ```git``` for the same reason why ```fetchurl``` uses ```buildPackages```'s ```curl```: to work smoothly in code blocks like
```
stdenv.mkDerivation {
src = fetchgit { # <- here git of buildPlatform is expected to work
.............
};
}
```

fetchgit: use buildPackages's git

---

pkgs/development/interpreters/perl/default.nix

https://security-tracker.debian.org/tracker/CVE-2018-18311

perl: 5.28.0 -> 5.28.1; 5.26.2 -> 5.26.3

---

pkgs/development/interpreters/perl/default.nix

Backport of https://github.com/NixOS/nixpkgs/pull/51450 to 18.09

[staging-18.09] perl: 5.28.0 -> 5.28.1, 5.26.2 -> 5.26.3

---

pkgs/tools/networking/freebind/default.nix
pkgs/top-level/all-packages.nix

IPv4 and IPv6 address rate limiting evasion tool
---

freebind: init at 2017-12-27

---

pkgs/applications/misc/tilix/default.nix
pkgs/tools/package-management/apt/default.nix

Fix ```Po4a``` paths left after https://github.com/NixOS/nixpkgs/pull/48959
cc @alesguzik @jtojnar

perlPackages.Po4a: fix lib path

---

pkgs/build-support/fetchurl/mirrors.nix

*   https://ftp.gwdg.de/pub/languages/perl/CPAN/ <- out of sync, 404 on some files (example: https://ftp.gwdg.de/pub/languages/perl/CPAN/src/5.0/perl-5.29.6.tar.gz)
*   https://download.xs4all.nl/mirror/CPAN/            <- out of sync, 404 on some files (example: https://download.xs4all.nl/mirror/CPAN/src/5.0/perl-5.29.6.tar.gz)
*   http://ftp.tuwien.ac.at/pub/CPAN/                      <- domain name not resolved
*   http://ftp.funet.fi/pub/CPAN/ <- nix fails with "unknown compression method 'x-gzip'" when using this mirror (nix does not like its 'Content-Encoding: x-gzip' in http headers)

mirrors.nix: remove bad cpan mirrors

---

pkgs/development/interpreters/perl/default.nix
pkgs/development/interpreters/perl/no-sys-dirs-5.29.patch

update devel branch
```no-sys-dirs-5.29.patch``` is slightly modified copy of ```no-sys-dirs-5.26.patch``` which fails to apply (it is possible to make an universal patch for ```perl``` and ```perldevel``` and reduce lines of code but it would require to rebuild ```perl``` and thus everything)
---

perldevel: 5.29.4 -> 5.29.6

---

pkgs/development/tools/build-managers/ninja/default.nix

re2c is used not for build docs, but for the main executable

ninja: re2c is not for building docs

---

pkgs/top-level/all-packages.nix

```cacert``` is used in ```fetchgit``` by ```git``` in ```nativeBuildInputs```, so by ```buildPackages.git```
As a data package ```buildPackages.cacert``` suppose to be equal to ```hostPackages.cacert```.
But ```hostPackages.cacert``` causes needless build of ```hostPackages.python``` and other packages, which takes time and requires them to support cross-compilation.
I am not sure why ```fetchgit``` needs the certificates. ```fetchurl``` works well without them skipping the certificate check (and allows to download from the websites with expired certificates - anyway ```sha256``` is checked afterwards). Doesn't ```git``` have an option like ```curl```'s ```-k``` ?

fetchgit: use buildPackages.cacert

---

pkgs/applications/networking/remote/xrdp/default.nix

Version update
[Changelog](https://github.com/neutrinolabs/xrdp/compare/v0.9.7..v0.9.9#diff-8312ad0561ef661716b48d09478362f3)
---

xrdp: 0.9.7 -> 0.9.9

---

pkgs/development/node-packages/default-v10.nix

fixes https://github.com/svanderburg/node2nix/issues/79#issuecomment-441526589
based on https://github.com/codaxy/cxjs/issues/279#issuecomment-335096573 `link:` is same as `file:`
Before build was failed with error https://pastebin.com/69G0DgKu
---

pnpm: fix build error "unsupported URL Type link"

---

pkgs/build-support/vm/default.nix

There is a function parameter ```kernel``` intended to specify which kernel to use.
It defaults to ```pkgs.linux```.
But when we override ```kernel```, compiling and using two kernels seems not to be the intendend bevavior.
https://github.com/NixOS/nixpkgs/blob/e64a5516036c03ef91ed0f0e45287462e09c6684/pkgs/build-support/vm/default.nix#L1-L2

runInLinuxVM: pkgs.linux -> kernel

---

pkgs/top-level/perl-packages.nix

Maxmind stopped distributing the ```v1```  database (https://github.com/NixOS/nixpkgs/issues/53953)
So let's start switching to ```v2```
---

perlPackages.GeoIP2: init at 2.006001

---

pkgs/build-support/build-fhs-userenv/env.nix
pkgs/build-support/buildenv/default.nix
pkgs/build-support/substitute-files/substitute-all-files.nix
pkgs/build-support/substitute/substitute-all.nix
pkgs/development/libraries/fontconfig/make-fonts-cache.nix

Building of every closure (even after minor changes in configuration.nix) requires Internet access (and get stuck in case of internet problems):
```
checking substituter 'http://cache.nixos.org' for path '/nix/store/1s9ihmx0sphd1p6hsyd39kscr2cgxn3c-stage-2-init.sh'
checking substituter 'http://cache.nixos.org' for path '/nix/store/cj7mj8g5ndm268gn0y1k0b8nzgackwf8-system-path'
querying info about '/nix/store/1s9ihmx0sphd1p6hsyd39kscr2cgxn3c-stage-2-init.sh' on 'http://cache.nixos.org'...
querying info about '/nix/store/cj7mj8g5ndm268gn0y1k0b8nzgackwf8-system-path' on 'http://cache.nixos.org'...
```
So, let's make ```buildEnv``` and ```substituteAll``` not to lookup in the binary caches as it is already done with many of the trivial builders.
Even if there is no problems with the Internet …

 buildEnv, substituteAll: disable binary cache lookups

---

nixos/modules/tasks/network-interfaces-scripted.nix

It is the second invocation of ```resolvconf```, missed in https://github.com/NixOS/nixpkgs/pull/32308
The fix was a part of https://github.com/NixOS/nixpkgs/pull/44986 which got stalled because other changes were controversial
Partially fixes https://github.com/NixOS/nixpkgs/issues/56681 (on systems which do not use ```resolvconf``` but still suffer from its failures)
cc @orivej @danbst 
Only ```${optionalString (!config.environment.etc?"resolv.conf")``` is added, the patch looks bigger because of the indentation change.

network-scripting: do not run resolvconf if /etc/resolv.conf is managed manually

---

pkgs/applications/graphics/image_optim/Gemfile
pkgs/applications/graphics/image_optim/Gemfile.lock
pkgs/applications/graphics/image_optim/default.nix
pkgs/applications/graphics/image_optim/gemset.nix
pkgs/applications/graphics/image_optim/update.sh
pkgs/applications/graphics/jpeg-archive/default.nix
pkgs/top-level/all-packages.nix

```
out=$(nix-build ./default.nix -A jpeg-archive)
$out/jpeg-archive --help # throws error, but it's should do so
$out/jpeg-compare --help
$out/jpeg-hash --help
$out/jpeg-recompress --help
sudo rm -rdf /tmp/test-images
mkdir -p /tmp/test-images
cp /nix/store/p98jdsj0vxjzsfdmff68frydk3db50m2-ruby2.5.3-image_optim-0.26.3/lib/ruby/gems/2.5.0/gems/image_optim-0.26.3/spec/images/icecream.gif /tmp/test-images/icecream.gif
cp /nix/store/p98jdsj0vxjzsfdmff68frydk3db50m2-ruby2.5.3-image_optim-0.26.3/lib/ruby/gems/2.5.0/gems/image_optim-0.26.3/spec/images/lena.jpg /tmp/test-images/lena.jpg
cp /nix/store/p98jdsj0vxjzsfdmff68frydk3db50m2-ruby2.5.3-image_optim-0.26.3/lib/ruby/gems/2.5.0/gems/image_optim-0.26.3/spec/images/rails.png /tmp/test-images/rails.png
cp …
```

image_optim: init at 0.26.3

---

maintainers/maintainer-list.nix
pkgs/servers/http/showoff/Gemfile
pkgs/servers/http/showoff/Gemfile.lock
pkgs/servers/http/showoff/default.nix
pkgs/servers/http/showoff/gemset.nix
pkgs/top-level/all-packages.nix

Wanted to use this application to introduce teammates to the nix toolset
Added ruby gem application showoff to nixpkgs
---

showoff: init at 0.20.1

---

pkgs/applications/networking/browsers/firefox/common.nix
pkgs/applications/networking/browsers/firefox/packages.nix

fix build, the same as for ```tor-browser-7-5```

firefox-esr-52: fix build

---

pkgs/applications/networking/remote/freerdp/default.nix

all ```x86_64``` have ```SSE2```, so it is needless

freerdp: remove 'optimize' parametes

---

pkgs/development/interpreters/perl/default.nix
pkgs/development/interpreters/perl/wrapper.nix
pkgs/development/perl-modules/generic/default.nix
pkgs/top-level/all-packages.nix
pkgs/top-level/perl-packages.nix

implement ```perl.withPackages``` after ```python``` and ```lua```
---
Tested on simple cases but might need review and more testing
```
$(nix-build -E "(import <nixpkgs> {}).perl.withPackages(p: [p.XMLParser])")/bin/perl \
-MXML::Parser -e 'print $XML::Parser::VERSION' 
```
---
test-driver with 
```
environment.systemPackages = with pkgs; [
(perl.withPackages(p: [p.XMLParser]))
];
```
---
Fixes https://github.com/NixOS/nixpkgs/issues/59042

perl: add .withPackages

---

pkgs/applications/graphics/djview/default.nix

Attempting to fix ```nixpkgs.config.firefox.enableDjvu = true;```
The plugins are in ```$out/lib/mozilla/plugins```.
```$out/lib/netscape/plugins``` does not exist

djview: fix mozilla plugin path

---

pkgs/applications/graphics/unigine-valley/default.nix

Reflect changes introduced in #37369
```valley``` failed to find ```libGL.so```

unigine-valley: fix loading libGL.so 

---

pkgs/development/interpreters/perl/default.nix
pkgs/top-level/perl-packages.nix

give priority to ```perl``` libraries when they meet the perl derivation in ```buildEnv```.
The notable case is ```buildEnv``` inside ```perl.withPackages```.
The ```perl``` derivation includes obsolete versions of some CPAN packages
which leads to collissions when there are newer versions
of the same libraries are on the right hand side
of ```perl.withPackages``` (perhaps indirectly).
Fixes #60025
https://github.com/NixOS/nixpkgs/commit/f73eb61113998952f742e3c542a9e95d9791abd4 is undone as no longer needed
@aanderse

perl.meta.priority += 1

---

pkgs/build-support/cc-wrapper/default.nix
pkgs/development/compilers/gcc/common/platform-flags.nix
pkgs/stdenv/generic/make-derivation.nix

Exceprt from #59148 needed to bootstrap post-#59225 ```staging``` with ```gcc.arch == "skylake"``` (mainly by avoiding to pass unsupported flags to bootstrap GCC and by preventing to build on the machines which did not declare their architecture as nix-build feature)

fix bootstrap when platform.gcc.arch=="skylake"

---

pkgs/top-level/perl-packages.nix

This undoes https://github.com/NixOS/nixpkgs/commit/6fb0e7a4e0fab0dd2f90a3c6eae8daf0ab40518d
The only problem with 6.04 is: it got new dependencies which fail to cross-compile.
Failure to cross-compile HTTP::Daemon leads to failure of LWP and XML::Parser, which are used in switch-to-configuration.pl
Thus upgrade HTTPDaemon from 6.01 to 6.04 broke cross-compilation of whole system closures.

perlPackages.HTTPDaemon: 6.04 -> 6.01

---

pkgs/development/libraries/libuv/default.nix

The test fails on non-NixOS Linuxes preventing to use them as remote builders
Fixes https://github.com/NixOS/nixpkgs/issues/57104
---

libuv: disable "get_passwd" test

---

nixos/modules/services/misc/nix-daemon.nix

following up #59148
I forgot the default case of the architectures which do not have minor brothers whose code they can run ("westmere" or any of AMDs)

nix.systemFeatures: minor fix

---

pkgs/applications/misc/hubstaff/default.nix
pkgs/applications/misc/hubstaff/revision.json
pkgs/applications/misc/hubstaff/update.sh

Hubstaff version 1.4.3 compiled atop of nixpkgs master is broken because of `segmentation fault  HubstaffClient` 
full log https://pastebin.com/raw/4K6r5CLr
Compiled atop of nixpkgs release-18.03 - broken too with `locale::facet::_S_create_c_locale name not valid` error https://github.com/NixOS/nixpkgs/issues/38988
But update script is working, can be merged
---

hubstaff: 1.3.1 → 1.4.5

---

pkgs/development/interpreters/perl/default.nix

There was a mix of overrideable-in-overlays ```buildPackages.perl528``` & ```buildPackages.perldevel``` and local ```perl528``` & ```perldevel``` which were unaffected by overlays
just a clean-up, it should not cause any rebuild (if ofborg will found rebuild, then I did something wrong here)

allow overriding perl528 and perldevel in overlays

---

nixos/modules/installer/tools/tools.nix

cross-compilation of `btrfs-tools` is broken, and this usually needless dependency of each system closure on `btrfs-tools` prevents cross-compilation of whole system closures

nixos-generate-config: do not build btrfs-tools when btrfs is not used

---

pkgs/development/interpreters/perl/default.nix
pkgs/top-level/all-packages.nix

perl530: init at 5.30.0

---

nixos/modules/services/x11/desktop-managers/enlightenment.nix
nixos/modules/services/x11/desktop-managers/lumina.nix
nixos/modules/services/x11/desktop-managers/lxqt.nix
nixos/modules/services/x11/desktop-managers/mate.nix
nixos/modules/services/x11/desktop-managers/maxx.nix
nixos/modules/services/x11/desktop-managers/plasma5.nix
nixos/modules/services/x11/desktop-managers/xterm.nix
nixos/modules/services/x11/xserver.nix

they can be used by remote desktop software, without X11 running locally
Fixes: https://github.com/NixOS/nixpkgs/issues/57717

nixos/desktop-managers: let them work when 'services.xserver.enable = false'

---

pkgs/applications/misc/hubstaff/default.nix
pkgs/applications/misc/hubstaff/revision.json

hubstaff: 1.4.5 -> 1.4.6

---

nixos/modules/installer/netboot/netboot.nix

Copy-paste from iso-image.nix
https://github.com/NixOS/nixpkgs/blob/ca7a18a24b4e54fb8ed2d756cd1c017e1aa67774/nixos/modules/installer/cd-dvd/iso-image.nix#L577-L579
Besides the simplification, it should use ```pkgs.buildPackages.squashfsTools``` because it is used in ```nativeBuildInputs``` instead of incorrect ```pkgs.squashfsTools``` which was forced by ```import```

nixos/netboot: import -> callPackage

---

pkgs/development/libraries/beignet/clang_llvm.patch
pkgs/development/libraries/beignet/default.nix
pkgs/top-level/all-packages.nix

Update ```beignet``` to the latest (yet abandoned an year ago) version, mainly for Coffee Lake support
See https://github.com/NixOS/nixpkgs/pull/55583#issuecomment-499558877
cc @gloaming @7c6f434c 
---
list of available OpenCL devices on ThinkPad P52, all work:

beignet: 1.3.2 -> unstable-2018.08.20

---

nixos/modules/module-list.nix
nixos/modules/programs/captive-browser.nix
pkgs/applications/networking/browsers/captive-browser/default.nix
pkgs/top-level/all-packages.nix

A dedicated Chromium instance to log into captive portals without messing with DNS settings
Related: https://github.com/NixOS/nixpkgs/issues/44972
cc @shazow @FiloSottile
I have not tested the ```networkd``` case
---

nixos/programs.captive-browser: init

---

pkgs/development/libraries/libvirt/default.nix
pkgs/development/python-modules/libvirt/default.nix
pkgs/top-level/perl-packages.nix

libvirt: 4.10.0 -> 5.3.0

---

pkgs/development/perl-modules/generic/builder.sh

some packages (for example Catmandu of https://github.com/NixOS/nixpkgs/pull/64137) has files with ```#!perl``` on first line which are not recognized as shebangs

buildPerlPackage: recognize "#!perl" as shebang

---

pkgs/development/libraries/gtkd/default.nix

```
$ nix-instantiate --show-trace -K -k -E "(import (builtins.fetchTarball https://github.com/NixOS/nixpkgs/archive/19.03.tar.gz) { config.allowAliases = false; }).gtkd"  
error: while evaluating the attribute 'glib' of the derivation 'gtkd-3.8.5' at /nix/store/72vjs9dvrj8nzsavl0i6j3n6dv62i8jl-source/pkgs/development/libraries/gtkd/default.nix:5:3:           
attribute 'glib' missing, at /nix/store/72vjs9dvrj8nzsavl0i6j3n6dv62i8jl-source/pkgs/development/libraries/gtkd/default.nix:4:26                                                             
```
@jtojnar

 gtkd: fix build with config.allowAliases=false

---

pkgs/top-level/perl-packages.nix

```buildPerlModule``` did not allow to specify hooks like ```preCheck``` or ```postInstall```
it also did not allow to override ```buildPhase``` or ```installPhase```
Working with hooks was a subtle difference between ```buildPerlPackage``` and ```buildPerlModule``` and replacing ```buildPerlPackage``` with ```buildPerlModule``` (or the other way around) resulted with unexpected effects.
@aanderse @srhb @rycee

perlPackages.buildPerlModule: allow pre/post hooks

---

pkgs/applications/misc/hubstaff/revision.json

hubstaff: 1.4.6 -> 1.4.9

---

pkgs/top-level/perl-packages.nix

Update `perlPackages` to the latest CPAN versions
Fixes #48857
Fixes #62278
Fixes #63230
Fixes #64137
@aanderse @rycee

perlPackages: update

---

pkgs/servers/nosql/arangodb/default.nix
pkgs/top-level/all-packages.nix

It depends on #59148 (it is used in a fork where #59148 is backported from)
---
cc maintainer @flosse

arangodb: 3.3.19 -> 3.2.18, 3.3.23.1, 3.4.7, 3.5.0-rc.7

---

pkgs/top-level/all-packages.nix

It works for me, but as it affects everything I cannot say that it is fully tested.
At least we will have time to test before making decision which `perl` will be default in `19.09`
`5.30.0` is about 3 month old and there were no urgent bugfixes or something like that, so it should be stable and already tested on bleeding edge distros.

perl: 5.28.2 -> 5.30.0

---

pkgs/development/compilers/graalvm/enterprise-edition.nix

graalvm8-ee: 19.1.1 -> 19.2.0

---

pkgs/applications/misc/hubstaff/revision.json

hubstaff: 1.4.9 -> 1.4.10

---

pkgs/tools/misc/megacli/default.nix

Other distros use direct url (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=megacli), so `requireFile` for a popular server package (used on many Hetzner servers) is an annoyance.

megacli: requireFile -> fetchurl

---

pkgs/applications/misc/hubstaff/revision.json

hubstaff: 1.4.10 -> 1.4.11

---

pkgs/applications/networking/dropbox/default.nix

dropbox: 73.4.118 -> 81.4.195

---

nixos/modules/services/mail/mailcatcher.nix

allow `mailcatcher` to bind to privileged ports

nixos/mailcatcher: add bind capabilities

---

nixos/modules/programs/less.nix
nixos/modules/services/mail/rspamd.nix
nixos/modules/services/monitoring/graphite.nix
nixos/modules/services/networking/prosody.nix
nixos/modules/services/web-apps/matomo.nix
nixos/modules/services/web-apps/restya-board.nix
nixos/modules/services/web-apps/tt-rss.nix
pkgs/applications/video/kino/default.nix
pkgs/development/tools/misc/ctags/wrapped.nix
pkgs/os-specific/darwin/apple-source-releases/system_cmds/default.nix
pkgs/tools/typesetting/tex/texlive/combine.nix

Nix parser is very relaxing and allows any character after `\` in strings
When the character following `\` is not one of the six which require escaping (`"` `r` `n` `$` `\` `t`) then `\` is silently skipped
so `"\1"` is the same as just`"1"`
This makes writing string constants which have `\` character (regular expressions, etc) challenging and error-prone.

treewide: fix string escapes

---

nixos/modules/tasks/network-interfaces.nix

https://github.com/NixOS/nixpkgs/pull/62835#pullrequestreview-285094670
@lheckemann

network-interfaces.nix: escape '.' in interface names passed to sysctl

---

pkgs/top-level/perl-packages.nix

There are many perl packages affected by https://github.com/NixOS/nixpkgs/issues/29637 and https://github.com/NixOS/nixpkgs/pull/71377#issuecomment-544276474
The fix might have to be moved to `buildPerlPackage`
I have not done it only because there are some packages already fixed this way, so doing it in 2 steps (fix the rest of packages and then refactor the fix into `buildPerlPackage`) seems less error-prone than concurrently fix new packages and refactor old ones.
cc @rycee @stigtsp @c0bw3b

perlPackages: fix i686-linux

---

pkgs/applications/misc/hubstaff/revision.json

hubstaff: 1.4.11 -> 1.5.0

---

pkgs/data/fonts/babelstone-han/default.nix

font version upgrade
`url` is the same, yes

babelstone-han: 12.1.4 -> 12.1.7

---

pkgs/applications/graphics/write_stylus/default.nix

error message was 
```
trying https://oyra.eu/write/icon.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download icon.tar.gz from any mirror
```
cc @

write_stylus: fix error "cannot download icon.tar.gz from any mirror"

---

pkgs/applications/misc/hubstaff/revision.json

hubstaff: 1.5.0 -> 1.5.2

---

pkgs/top-level/perl-packages.nix

https://metacpan.org/pod/LWP::UserAgent::DNS::Hosts
cc @

perlPackages.LWPUserAgentDNSHosts: init at 0.13

---

nixos/modules/services/networking/nat.nix

The motivations are:
1. to add `nixos-nat-out` along with `nixos-nat-pre` and `nixos-nat-post` to support scenarios when output packets are NAT'ed to another destination.
Examples are: 
* a webmaster may want to to redirect "website.com:80" and "website.com:443" to unprivileged ports on 127.0.0.1 where a webserver is running.
* TOR and I2P websites [can be mapped to](https://www.grepular.com/Transparent_Access_to_Tor_Hidden_Services) private address space.
Those techniques require adding NAT rules to OUTPUT chain along with PREROUTING and POSTROUTING so it would be nice if all NAT rules will be set and cleaned at once.
2. adding `nixos-nat-out`, `nixos-nat-pre` and `nixos-nat-post` to `ip6tables` would simplify setting up NAT66 (i know it is an anti-pattern, but sometimes inevitable). …

nixos/nat: create nixos-nat-{pre,post,out} in ip6tables too

---

nixos/modules/services/networking/unbound.nix

because overriding `pkgs.unbound` in overlay causes mass-rebuild

nixos/unbound: add package option

---

nixos/modules/services/networking/nat.nix

It should be part of https://github.com/NixOS/nixpkgs/pull/68459 but I forgot :(
Using `nixos-nat-out` instead of `OUTPUT` cleans up the rule on `nat` service stop

nixos/nat: use nixos-nat-out instead of OUTPUT

---

nixos/modules/module-list.nix
nixos/modules/programs/traceroute.nix

`mtr` might be fancier, but it lacks some options (for example `--interface=device`), so it cannot replace old good `traceroute`

nixos/traceroute: init

---

pkgs/development/interpreters/perl/wrapper.nix

`perl.withPackages` did not allow to add more packages using `$PERL5LIB`
reported by @ljli at https://github.com/NixOS/nixpkgs/pull/77996#issuecomment-575985659

perl.withPackages: respect $PERL5LIB

---

pkgs/development/compilers/graalvm/enterprise-edition.nix
pkgs/top-level/all-packages.nix

graalvm8-ee: 19.2.1 -> 19.3.1, graalvm11-ee: init at 19.3.1

---

nixos/modules/system/activation/activation-script.nix

Add option to install symlink to `ld-linux(8)` system-wide to allow running unmodified ELF binaries.
It might be useful to run games or executables distributed inside jar files as discussed
https://discourse.nixos.org/t/runtime-alternative-to-patchelf-set-interpreter/3539
https://discourse.nixos.org/t/running-binaries-without-fhs-and-patchelf/1828
It is the third concession to FHS after `/bin/sh` and `/usr/bin/env`,
but unlike `config.environment.binsh` and `config.environment.usrbinenv` this new option is disabled by default
cc @

add config.environment.ld-linux

---

pkgs/development/tools/pretty-simple/default.nix
pkgs/top-level/all-packages.nix

pretty-simple: init at 3.2.1.0

---

nixos/lib/qemu-flags.nix
nixos/tests/installer.nix

`kvm64` is the most generic CPU, which does not support SSE4.2, AVX and other ISA extentions.
There are already some packages which use extended opcodes. They cannot be run in VM.
With the acceptance of https://github.com/NixOS/nixpkgs/pull/59225 and https://github.com/NixOS/nixpkgs/pull/59148 even ```glibc``` would have AVX instructions in ```memcpy()``` code (if ```platform.gcc.arch``` is at least ```sandybridge```) so almost all the packages from host's nix store shared with the VM via 9p won't run in the VM if the the VM does not have the same CPU as the host.

runInLinuxVM, test-driver: pass host's cpu type to guest vm

---

pkgs/development/compilers/oraclejdk/jdk-linux-base.nix

`config.oraclejdk.accept_license` does nothing after `oraclejdk8: 8u211 -> 8u241` #77783.
Actually, since few month already, since it is not possible to download `oraclejdk` using `curl`

oraclejdk8: remove dead code

---

pkgs/applications/misc/far2l/default.nix

1. version update
2. remove "unstable" which is confusing as there is no stable version at all (fixes https://github.com/NixOS/nixpkgs/issues/74490)
3. use fixed syntax highlighting schemes which are not yet included in `far2l`
4. `name` -> `pname`
cc @

far2l: 2018-07-19 -> 2019-12-14

---

pkgs/development/libraries/qt-5/5.12/default.nix

pick upstream patch for [QTBUG-78937](https://bugreports.qt.io/browse/QTBUG-78937)
Fixes https://github.com/NixOS/nixpkgs/issues/81769

qt512: pick upstream patch for QTBUG-78937

---

nixos/modules/system/activation/top-level.nix

`$toplevel/system` of a system closure with `x86_64` kernel and `i686` userland should contain "x86_64-linux".
If `$toplevel/system` contains "i686-linux", the closure will be run using `qemu-system-i386`, which is able to run `x86_64` kernel on most Intel CPU, but fails on AMD.
So this fix is for a rare case of `x86_64` kernel + `i686` userland + AMD CPU
cc @Ericson2314 @matthewbauer

$toplevel/system: use kernel's architecture

---

pkgs/tools/security/scallion/default.nix

it does not work with openssl 1.1 (upstream issue https://github.com/lachesis/scallion/issues/113)

scallion: use openssl 1.0

---

pkgs/development/interpreters/perl/default.nix

perl: 5.30.1 -> 5.30.2

---

pkgs/applications/networking/browsers/firefox/packages.nix

Since Firefox 60, build on 32-bit platforms fails with "out of memory".
32-bit platforms are not excluded from `meta.platforms` nor added to `meta.badPlatforms` because this is not limitation of host platform.
Cross-compilation of 32-bit `firefox` on 64-bit machine might work.

firefox: mark as broken on 32-bit buildPlatform

---

pkgs/applications/editors/jedit/default.nix
pkgs/applications/version-management/git-and-tools/bfg-repo-cleaner/default.nix
pkgs/build-support/fetchmavenartifact/default.nix
pkgs/build-support/fetchurl/mirrors.nix
pkgs/servers/monitoring/prometheus/jmx-httpserver.nix
pkgs/tools/networking/openapi-generator-cli/default.nix

Domain `central.maven.org` does not exist
```
; <<>> DiG 9.14.11 <<>> central.maven.org @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 50804
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;central.maven.org.		IN	A
;; AUTHORITY SECTION:
maven.org.		853	IN	SOA	ns-1965.awsdns-53.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
;; Query time: 5 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Fri Jun 12 14:27:41 UTC 2020
;; MSG SIZE  rcvd: 133
```

treewide: central.maven.org -> repo1.maven.org

---

nixos/modules/module-list.nix
nixos/modules/services/networking/onedrive.nix
nixos/modules/services/networking/onedrive.xml

Continues #77734  (GitHub login issues caused me to make another account)
cc: @peterhoeg 
I have addressed your two comments: 
1) Rename the service from `onedriveLauncher` to `onedrive-launcher`.
2) Remove useless `network-online.target` targets from user service.

nixos/onedrive: init

---

pkgs/development/compilers/oraclejdk/jdk11-linux.nix
pkgs/development/compilers/oraclejdk/jdk14-linux.nix
pkgs/top-level/all-packages.nix

Newer Oracle JDKs
In newer Oracle JDKs there is no Mozilla Plugins, no `javaws`, no JRE, no platforms other than `x84_64-linux`, so they are much simpler than `oraclejdk8`.
Basically `unzip` then `patchelf`
Fixes: https://github.com/NixOS/nixpkgs/issues/93500

oraclejdk11: init at 11.0.8, oraclejdk14: init at 14.0.2

---

nixos/modules/system/boot/systemd.nix
nixos/modules/tasks/network-interfaces-scripted.nix

in LXC container /dev/net/tun is pre-available, "dev-net-tun.device" always fails
From the comment https://github.com/NixOS/nixpkgs/issues/9735#issuecomment-500164017

fix TUN networking in LXC containers

---

lib/systems/architectures.nix
lib/systems/default.nix
nixos/modules/services/misc/nix-daemon.nix
pkgs/applications/science/math/nauty/default.nix
pkgs/build-support/cc-wrapper/default.nix
pkgs/development/interpreters/j/default.nix
pkgs/development/libraries/dlib/default.nix
pkgs/development/libraries/fflas-ffpack/default.nix
pkgs/development/libraries/g2o/default.nix
pkgs/development/libraries/givaro/default.nix
pkgs/development/libraries/linbox/default.nix
pkgs/development/libraries/qt-5/modules/qtbase.nix
pkgs/development/python-modules/dlib/default.nix
pkgs/development/python-modules/tensorflow/1/default.nix
pkgs/development/python-modules/tensorflow/2/default.nix
pkgs/servers/nosql/arangodb/default.nix
pkgs/tools/misc/cpuminer-multi/default.nix
pkgs/tools/networking/i2pd/default.nix

support for AMD CPUs in ```localSystem.hostPlatform.platform.gcc.arch```
I have (or can rent) a test park of
cc: @matthewbauer @7c6f434c

platform.gcc.arch: support for AMD CPUs

---

nixos/modules/services/networking/onedrive.nix

I have decided that verbose isn't appropriate for a "production" service. 
[x] Fits contributing.md

nixos/onedrive: Remove verbose flag

---

pkgs/development/tools/database/shmig/default.nix

shmig: fix `migrate` command when postgres is enabled

---

pkgs/applications/networking/browsers/chromium/common.nix

ld.gold outs of memory on i686.
I am not sure why ld.gold is needed at all, probably `use_gold = false;` would be a better option.
I kept it `true` on 64-bit platforms only to avoid rebuild

chromium: fix build on i686

---

pkgs/applications/networking/browsers/chromium/common.nix
pkgs/applications/networking/browsers/ungoogled-chromium/common.nix

`chromium` is built on half of `$NIX_BUILD_CORES` due to an old Hydra out of memory issue.
Nowadays, when hardware typically has more memory and cores, this increases build time twofold causing build timeouts.
Also, the most memory consuming task is `ld.gold` linker which works on single-core anyway and @TredwellGit is going to get rid of it (https://github.com/NixOS/nixpkgs/pull/100512#issuecomment-709356964).
Fixes #100486
Related #78347 #100512
cc @vcunat @thefloweringash @TredwellGit

chromium: build on all cores

---

pkgs/applications/misc/hubstaff/revision.json

hubstaff: 1.5.2 -> 1.5.7

---

pkgs/top-level/impure.nix

before `builtins.fn` and `fn` were mixed, now they are not mixed
- made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#genera …

top-level/impure.nix: refactor by removing 'with builtins'

---

pkgs/tools/misc/debootstrap/default.nix

Added various binaries to `PATH` in the `debootstrap`'s wrapper.
`xz` package is needed to support package archives that only provide `Packages.xz` and not `Packages`.
`binutils` provides `ar`, which `debootstrap` can optionally use to extract `*.deb` files instead of using `dpkg-deb`.
`bzip2` provides `bunzip2`, which `debootstrap` may use when dealing with archives that only provide compressed files in the compatible format.
- or, for functions and "core" functionality, tests in …

debootstrap: fix to support archives that only provide Packages.xz

---

pkgs/tools/misc/cowsay/default.nix

Cowsay currently cannot find its pre-installed cowfiles when installed into the user or system profile, failing with:
```
cowsay: Could not find cowfile for 'default.cow'!
```
This patch adds a wrapper that explicitly sets the COWPATH environment variable to fix this.
- made sure NixOS tests are …

cowsay: add COWPATH wrapper

---

nixos/modules/config/malloc.nix

Increase `vm.max_map_count` sysctl when using the `graphene-hardened` memory allocator, as otherwise it will break your system in terrible ways. For example, `nixos-rebuild` will almost certainly no longer work and fail with `error: out of memory`.
This setting is mandated in the https://github.com/GrapheneOS/hardened_malloc#traditional-linux-based-operating-systems README, but this change will prevent people breaking their system if they don't RTFM.
I'd actually recommend `graphene-hardened` over `scudo` for the hardened profile, as in my limited testing, it seems to break less things. `scudo` deadlocks on a `futex()` call if another LD_PRELOADed library tries to allocate memory, which breaks things like torsocks. `graphene-hardened` does not have this issue.
- …

nixos/malloc: set vm.max_map_count when using graphene-hardened

---

pkgs/tools/networking/gsocket/default.nix

https://github.com/hackerschoice/gsocket/releases/tag/v1.4.40
- made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generatin …

gsocket: 1.4.39 -> 1.4.40

---

nixos/modules/system/boot/loader/grub/memtest.nix
nixos/modules/system/boot/loader/systemd-boot/systemd-boot.nix
nixos/tests/systemd-boot.nix

Now that Memtest86+ supports UEFI and the 64-bit Linux boot handover protocol, we can use that on UEFI systems instead of falling back to the proprietary Passmark Memtest86. 
GRUB2 no longer needs any special handling for booting memtest86+ on UEFI systems, as it can be booted both using the 64-bit Linux handover protocol on UEFI and 16-bit Linux handover on legacy systems. 
This allows for a better implementation than #225616 for GRUB2, because we don't need any special handling for UEFI anymore, it can use the same entry/binary as legacy boot, and still accept boot params in UEFI.
On systemd-boot we need to use the new UEFI binary as in #225616.
- [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside …

nixos/grub, nixos/systemd-boot: Replace proprietary Memtest86 with free Memtest86+ on NixOS systems with UEFI

---

pkgs/applications/misc/terminal-typeracer/default.nix

Changelog:
https://gitlab.com/ttyperacer/terminal-typeracer/-/releases/v2.0.9
https://gitlab.com/ttyperacer/terminal-typeracer/-/releases/v2.0.10
https://gitlab.com/ttyperacer/terminal-typeracer/-/releases/v2.0.12
https://gitlab.com/ttyperacer/terminal-typeracer/-/releases/v2.0.13
https://gitlab.com/ttyperacer/terminal-typeracer/-/releases/v2.1.0
https://gitlab.com/ttyperacer/terminal-typeracer/-/releases/v2.1.1
https://gitlab.com/ttyperacer/terminal-typeracer/-/releases/v2.1.2
https://gitlab.com/ttyperacer/terminal-typeracer/-/releases/v2.1.3
- and/or [package …

terminal-typeracer: 2.0.8 -> 2.1.3

---

pkgs/applications/misc/hubstaff/default.nix

I've got an email 
```
Hello,
I'm the Tech Lead of the Client Desktop team at Hubstaff and saw that you are the maintainers of the hubstaff nixOS package!?
We just got a notification from one of our clients. He patched it for his own use and asked about upstreaming it:
https://github.com/allgreed/nixos-config/commit/7402b23e8285b5094e5b3ca2b3845cb2aaf66063
The thing is we don't support nixOS unfortunately (I'm personally a big fan though!).
Any chance you guys can update that? If you need any more information please just let me know!
We also have a RSS feed with the newest releases (just look for the "enclosure" and sparkle:os="linux"):
https://app.hubstaff.com/appcast.xml
The latest linux release is:
https://app.hubstaff.com/download/7473-standard-linux-1-6-24-release
Thanks,
Artur
``` …

hubstaff: change updateScript url to use new RSS feed

---

pkgs/by-name/de/debian-devscripts/package.nix

Diff: https://salsa.debian.org/debian/devscripts/-/compare/refs/tags/v2.25.15...v2.25.16 …

debian-devscripts: 2.25.15 -> 2.25.16

---

pkgs/by-name/ln/lnav/package.nix

https://github.com/tstack/lnav/releases/tag/v0.13.0
https://github.com/tstack/lnav/compare/v0.12.4...v0.13.0 …

lnav: 0.12.4 -> 0.13.0

---

pkgs/by-name/ab/ablog/package.nix

ablog: disable failed test

---

pkgs/by-name/lu/lux-cli/package.nix
pkgs/development/lua-modules/lux-lua.nix

Changed repo owner to lumen-oss after org rename. 
[pkgs/test]: …

lux-cli: 0.17.0 -> 0.17.1
