- pkgs/development/tools/profiling/systemtap/default.nix
Old version does not work with kernel 4.9 which is now the default for nixos 17.03
on non-NixOS)
---
> systemtap: 2016-09-16 -> 2017-02-04

- pkgs/applications/virtualization/virt-viewer/default.nix
- pkgs/development/libraries/spice-gtk/default.nix
- pkgs/top-level/all-packages.nix
version update
on non-NixOS)
---
> virt-viewer: 2.0 -> 5.0

- nixos/modules/virtualisation/libvirtd.nix
- pkgs/applications/virtualization/virt-manager/default.nix
- pkgs/development/libraries/libvirt-glib/default.nix
- pkgs/development/libraries/libvirt/default.nix
- pkgs/top-level/python-packages.nix
> libvirt: 3.0.0 -> 3.1.0

- pkgs/tools/networking/reaver-wps-t6x/default.nix
- pkgs/tools/networking/reaver-wps/default.nix
Fixes #25297
on non-NixOS)
---
> reaver: database on readwrite medium

- pkgs/applications/editors/jetbrains/update.pl
follow up https://github.com/NixOS/nixpkgs/pull/26769#pullrequestreview-45801618
use ```perlPackages.LWPProtocolhttps``` because urls of .sha256-files could be https://
> jetbrains updater: use perlPackages.LWPProtocolhttps

- pkgs/applications/networking/syncthing/default.nix
> syncthing: typo

- pkgs/development/python-modules/amqplib/default.nix
Fixes https://github.com/NixOS/nixpkgs/issues/27732
> pythonPackages.amqplib: pypi->github

- pkgs/applications/networking/remote/xrdp/default.nix
> xrdp: 0.9.2->0.9.3

- pkgs/servers/zookeeper/default.nix
Minor update ([changelog](http://zookeeper.apache.org/doc/r3.4.10/releasenotes.html))
> zookeeper: 3.4.9 -> 3.4.10

- pkgs/development/tools/misc/ccache/default.nix
An independent part of https://github.com/NixOS/nixpkgs/pull/28022
> ccacheWrapper: extraConfig does not handle special characters

- pkgs/data/fonts/font-awesome-ttf/default.nix
> font-awesome-ttf: make the font derivation fixed-output

- pkgs/data/fonts/wqy-zenhei/default.nix
> wqy_zenhei: make the font derivation fixed-output

- pkgs/data/fonts/wqy-microhei/default.nix
> wqy_microhei: make the font derivation fixed-output

- pkgs/data/fonts/vista-fonts/default.nix
> vistafonts: make the font derivation fixed-output

- pkgs/data/fonts/ubuntu-font-family/default.nix
> ubuntu_font_family: make the font derivation fixed-output

- pkgs/data/fonts/iosevka/default.nix
> iosevka: make the font derivation fixed-output

- pkgs/data/fonts/marathi-cursive/default.nix
> marathi-cursive: make the font derivation fixed-output

- pkgs/data/fonts/ipaexfont/default.nix
> ipaexfont: make the font derivation fixed-output

- pkgs/data/fonts/ipafont/default.nix
> ipafont: make the font derivation fixed-output

- pkgs/data/fonts/liberastika/default.nix
> liberastika: make the font derivation fixed-output

- pkgs/data/fonts/gentium-book-basic/default.nix
- pkgs/data/fonts/gentium/default.nix
> gentium: source link fixed

- pkgs/data/fonts/bakoma-ttf/default.nix
> bakoma_ttf: dead link fixed

- pkgs/data/fonts/noto-fonts/default.nix
> noto-fonts, noto-fonts-cjk: make the font derivation fixed-output

- pkgs/data/fonts/arphic/default.nix
> arphic-ukai, arphic-uming: make the font derivation fixed-output

- pkgs/data/fonts/redhat-liberation-fonts/default.nix
> liberation_ttf: make derivation fixed-output

- pkgs/data/fonts/dejavu-fonts/default.nix
> dejavu_fonts: made derivation fixed-output

- pkgs/build-support/fetchurl/mirrors.nix
removed dead mirrors, added new
> mirrors: update apache and cpan mirrors

- pkgs/development/compilers/haxe/default.nix
> haxe: 3.4.2 -> 3.4.3

- pkgs/development/libraries/liboping/default.nix
> liboping: 1.9.0 -> 1.10.0

- pkgs/development/libraries/libmicrohttpd/default.nix
> libmicrohttpd: fix darwin build

- pkgs/tools/system/collectd/default.nix
> collectd: fix darwin build

- pkgs/applications/misc/far2l/default.nix
> far2l: unstable-2017-07-13 -> unstable-2017-09-30, fix darwin build

- pkgs/development/compilers/haxe/default.nix
> haxe: 3.4.3 -> 3.4.4

- pkgs/data/fonts/inconsolata/lgc.nix
- pkgs/data/fonts/libertine/default.nix
- pkgs/data/fonts/monoid/default.nix
- pkgs/data/fonts/rictydiminished-with-firacode/default.nix
- pkgs/data/fonts/unscii/default.nix
- pkgs/data/fonts/xits-math/default.nix
> data/fonts: make derivations fixed-outputs (fontforge group)

- pkgs/servers/sql/postgresql/timescaledb/default.nix
> timescaledb: 0.5.0 -> 0.6.0

- pkgs/applications/networking/browsers/opera/default.nix
> opera:	46.0.2597.39	->	48.0.2685.52

- pkgs/applications/misc/far2l/add-nix-syntax-highlighting.patch
- pkgs/applications/misc/far2l/default.nix
* minor version bump
* minor fixes in Nix highlighter
* aarch64 support https://github.com/elfmz/far2l/pull/309
> far2l: unstable-2017-09-30 -> unstable-2017-10-08

- pkgs/applications/networking/remote/freerdp/default.nix
> freerdp: fix aarch64 build

- nixos/modules/module-list.nix
- nixos/modules/programs/ccache.nix
Mechanize the [textual instruction from ```all-packages.nix```](https://github.com/NixOS/nixpkgs/blob/031d627/pkgs/top-level/all-packages.nix#L6673-L6692) on how to configure ccache
Fixes https://github.com/NixOS/nixpkgs/issues/27782
> nixos/ccache: init

- pkgs/servers/zookeeper/default.nix
> zookeeper: 3.4.10 -> 3.4.11

- pkgs/development/tools/coursier/default.nix
update the latest Release Candidate to release version
> coursier: 1.0.0-RC13 -> 1.0.0

- pkgs/development/compilers/haxe/default.nix
> haxe: 3.4.4 -> 3.4.6

- pkgs/data/fonts/babelstone-han/default.nix
> babelstone-han: 10.0.0 -> 10.0.2

- pkgs/applications/misc/dockbarx/default.nix
> dockbarx: 0.92 -> 0.93

- nixos/modules/services/networking/nat.nix
Attempt to fix #35132
endpoints defined in ```nat.forwardPorts``` can be connected from the Internet, but also
That requires a tricky technique called NAT reflection https://unix.stackexchange.com/questions/282086/how-does-nat-reflection-nat-loopback-work
> nixos/nat: support nat reflection

- pkgs/servers/varnish/default.nix
- pkgs/servers/varnish/modules.nix
- pkgs/servers/varnish/rtstatus.nix
> varnish: 5.1.3 -> 5.2.1 [fixes CVE-2017-8807]

- pkgs/tools/networking/tinc/default.nix
> tinc: 1.0.32 -> 1.0.33

- pkgs/servers/varnish/modules.nix
> varnish-modules: 0.10.2 -> 0.13.0

- pkgs/applications/editors/jetbrains/default.nix
> jetbrains-editors: minor updates

- pkgs/data/misc/mime-types/default.nix
> data/mime-types: make derivation fixed-output

- pkgs/development/libraries/libguestfs/default.nix
> libguestfs: 1.36.3 -> 1.38.0

- pkgs/development/libraries/protobuf/3.5.nix
- pkgs/top-level/all-packages.nix
Version update.
Have not tested all the deps, so the PR is against ```staging```
> protobuf: 3.4.0 -> {3.4.1, 3.5.1.1}

- pkgs/development/libraries/sqlite/default.nix
- pkgs/development/libraries/sqlite/sqlite3_analyzer.nix
Version update.
No breaking changes, only fixes and added features: https://www.sqlite.org/releaselog/3_22_0.html
> sqlite: 3.21.0 -> 3.22.0

- nixos/release.nix
nixos/tests: add forgotten xrdp.nix
> nixos/tests: add forgotten xrdp.nix

- pkgs/tools/networking/dropbear/default.nix
> dropbear: 2017.75 -> 2018.76

- nixos/modules/services/networking/nix-serve.nix
- pkgs/tools/package-management/nix-serve/default.nix
> nix-serve: nix 2.0 fixes

- pkgs/tools/typesetting/docbook2x/default.nix
- pkgs/top-level/all-packages.nix
- pkgs/top-level/perl-packages.nix
@shlevy try this instead of 
https://github.com/NixOS/nixpkgs/commit/89700d7b26c5c3877321e29893f21445bd0e8da8
> perlPackages.XMLSAX: 0.96 -> 1.00 [staging]

- pkgs/tools/security/sshuttle/default.nix
Fixes https://github.com/NixOS/nixpkgs/issues/36969
> sshuttle: fix build on i686-linux

- pkgs/development/tools/java/cfr/default.nix
> cfr: 0_101 -> 0_125

- pkgs/applications/misc/far2l/add-nix-syntax-highlighting.patch
- pkgs/applications/misc/far2l/default.nix
> far2l: 2017-10-08 -> 2018-02-27

- pkgs/applications/science/misc/gephi/default.nix
- pkgs/development/java-modules/jogl/default.nix
- pkgs/top-level/java-packages.nix
> gephi: build from sources

- pkgs/development/java-modules/jogl/default.nix
- pkgs/top-level/java-packages.nix
dependency of #36851 and #37356
> jogl: init at 2.3.2

- pkgs/applications/audio/rhvoice/default.nix
- pkgs/applications/audio/rhvoice/honor_nix_environment.patch
- pkgs/top-level/all-packages.nix
Duplicate of https://github.com/NixOS/nixpkgs/pull/32979 just to run tests
> rhvoice: init at 0.6.unstable-2018-02-10

- pkgs/desktops/xfce/core/xfce4-panel.nix
- pkgs/desktops/xfce/core/xfwm4.nix
Minor bump in stable branch (mostly fixes in text translations)
>  xfce.xfce4-panel: 4.12.1 -> 4.12.2;  xfce.xfwm4: 4.12.3 -> 4.12.4

- pkgs/development/libraries/libguestfs/default.nix
minor fix after https://github.com/NixOS/nixpkgs/pull/37562
> libguestfs: doInstallCheck only with appliance

- nixos/modules/tasks/network-interfaces.nix
`wlanDeviceUdevScript` is not used below in the text
> network-interfaces.nix: dead code removal

- pkgs/top-level/perl-packages.nix
> perlPackages.GD: fix build on staging

- pkgs/top-level/perl-packages.nix
newer ```cpan2nix``` run
supersede https://github.com/NixOS/nixpkgs/pull/40441
> [staging] cpan2nix: update perl packages

- pkgs/development/perl-modules/BerkeleyDB/default.nix
> perlPackages.BerkeleyDB: 0.54 -> 0.55

- pkgs/top-level/perl-packages.nix
> perlPackages.ListBinarySearch: 0.20 -> 0.25

- pkgs/development/perl-modules/DB_File/default.nix
> perlPackages.DB_File: 1.831 -> 1.841

- pkgs/development/perl-modules/Compress-Raw-Zlib/default.nix
> perlPackages.CompressRawZlib: 2.074 -> 2.081

- pkgs/top-level/perl-packages.nix
> perlPackages.FileDesktopEntry: 0.04 -> 0.22

- pkgs/development/perl-modules/DBD-mysql/default.nix
> perlPackages.DBDmysql: 4.041 -> 4.046

- pkgs/top-level/perl-packages.nix
update to match ```JSON::PP``` version
> perlPackages.JSON: 2.90 -> 2.97001

- pkgs/development/perl-modules/DBD-Pg/default.nix
> perlPackages.DBDPg: 3.5.3 -> 3.7.4

- pkgs/development/libraries/libvirt/default.nix
- pkgs/development/python-modules/libvirt/default.nix
- pkgs/top-level/perl-packages.nix
> libvirt: 4.1.0 -> 4.4.0

- pkgs/development/java-modules/jogl/default.nix
Reflect changes introduced in https://github.com/NixOS/nixpkgs/pull/37369
Fixes https://github.com/NixOS/nixpkgs/issues/41730
@abbradar
> jogl: reflect recent changes in opengl

- nixos/modules/tasks/network-interfaces.nix
this code block repeated few lines below
> network-interfaces.nix: remove duplicate code

- pkgs/top-level/perl-packages.nix
following another staging/master merge
@rycee
> [staging] cpan2nix updates

- pkgs/development/perl-modules/CatalystXScriptServerStarman-fork-arg.patch
> [staging] perlPackages.CatalystXScriptServerStarman: fix build

- pkgs/top-level/perl-packages.nix
> perl-packages.nix: duplicate packages -> aliases

- pkgs/top-level/perl-packages.nix
> perlPackages.PathTools: 3.47 -> 3.74

- pkgs/development/interpreters/perl/default.nix
minor update
bugfixes including 3 CVE
https://metacpan.org/pod/distribution/perl/pod/perl5244delta.pod
https://metacpan.org/pod/distribution/perl/pod/perl5262delta.pod
> [staging] [security] perl524: 5.24.3 -> 5.24.4; perl526: 5.26.1 -> 5.26.2

- pkgs/tools/graphics/pngquant/default.nix
> pngquant: 2.11.7 -> 2.12.1

- pkgs/development/compilers/graalvm/default.nix
> graalvm8: 1.0.0-rc1 -> 1.0.0-rc3

- pkgs/top-level/perl-packages.nix
> perlPackages: fix meta and fix build with perl-5.26

- pkgs/development/libraries/pcre2/default.nix
update to the version which includes patches and passes tests
> [staging] pcre2: 10.23 -> 10.31

- pkgs/development/libraries/pcre/default.nix
> [staging] pcre: 8.41 -> 8.42

- pkgs/development/libraries/libvirt/default.nix
- pkgs/development/python-modules/libvirt/default.nix
- pkgs/top-level/perl-packages.nix
> libvirt: 4.4.0 -> 4.5.0

- pkgs/applications/networking/browsers/chromium/plugins.nix
- pkgs/applications/networking/browsers/mozilla-plugins/flashplayer/default.nix
- pkgs/applications/networking/browsers/mozilla-plugins/flashplayer/standalone.nix
> flash: 30.0.0.113 -> 30.0.0.134

- pkgs/applications/misc/mucommander/default.nix
Fixes https://github.com/NixOS/nixpkgs/issues/36982
> mucommander: fix crash under XFCE

- pkgs/applications/graphics/processing3/default.nix
Fixes https://github.com/NixOS/nixpkgs/issues/36982
> processing3: fix crash under XFCE, fix build in sandbox

- pkgs/desktops/xfce/applications/orage.nix
- pkgs/desktops/xfce/core/xfce4-panel.nix
- pkgs/desktops/xfce4-13/orage/default.nix
- pkgs/desktops/xfce4-13/xfce4-panel/default.nix
fix tzdata path (for timezone selector to work)
> orage: "/usr/share/zoneinfo" -> "${tzdata}/share/zoneinfo"

- pkgs/desktops/xfce4-13/thunar/default.nix
> thunar: 1.7.0 -> 1.8.1

- pkgs/desktops/xfce4-13/tumbler/default.nix
> tumbler: 0.2.0 -> 0.2.1

- pkgs/development/libraries/wxwidgets/3.0/default.nix
minor update
remove patch accepted by upstream
expose version
---
> wxGTK30: 3.0.3.1 -> 3.0.4

- pkgs/development/r-modules/default.nix
To fix https://github.com/NixOS/nixpkgs/commit/52f53c69ce6dbc5538f7e4cd22f9d93baf1f64a2#r29957404
@ryantm
> r-packages: fix regression

- pkgs/development/compilers/graalvm/default.nix
> graalvm: fix dead url

- pkgs/applications/networking/cluster/hadoop/default.nix
> hadoop_2_7: 2.7.6 -> 2.7.7; hadoop_3_1: 3.1.0 -> 3.1.1

- pkgs/development/interpreters/perl/default.nix
remove duplicated code
the same substitution is made in ```postPatch``` few lines above: https://github.com/NixOS/nixpkgs/pull/45256/files#diff-d3d0e3e7faa9701cb861ff9307f251f7R58
> perl: remove duplicated code

- pkgs/development/perl-modules/DB_File/default.nix
- pkgs/top-level/perl-packages.nix
perl packages version bump
the last before 18.09 branch off?
> perlPackages: cpan2nix updates

- nixos/doc/manual/release-notes/rl-1809.xml
- nixos/modules/config/iproute2.nix
- pkgs/os-specific/linux/iproute/default.nix
Alternative for https://github.com/NixOS/nixpkgs/pull/39536 without recompiling customized version of ```iproute``` and without altering /etc/iproute2 to /run/iproute2
See discussion here https://github.com/NixOS/nixpkgs/pull/39536
cc @teto
> iproute: copy files in /etc

- pkgs/top-level/perl-packages.nix
> cpan2nix updates

- pkgs/development/libraries/libvirt/default.nix
- pkgs/development/python-modules/libvirt/default.nix
- pkgs/top-level/perl-packages.nix
> libvirt: 4.5.0 -> 4.7.0

- pkgs/development/libraries/liblangtag/default.nix
> language_subtag_registry: fix hash

- pkgs/tools/misc/coreutils/default.nix
Fix cross build broken in https://github.com/NixOS/nixpkgs/pull/45720
> coreutils-full: fix cross build

- pkgs/tools/archivers/p7zip/default.nix
> p7zip: fix cross-compilation

- pkgs/os-specific/linux/psmisc/default.nix
> psmisc: fix cross-compiling

- pkgs/tools/networking/ntp/default.nix
> ntp: fix cross-build

- pkgs/tools/text/dos2unix/default.nix
> dos2unix: fix cross build

- pkgs/top-level/perl-packages.nix
https://github.com/NixOS/nixpkgs/pull/48241 + 
https://github.com/NixOS/nixpkgs/pull/48242 +
https://github.com/NixOS/nixpkgs/pull/48246 rebased to staging 
Needed for cross-compilation of whole closures (as dependency of switch-to-configuration.pl)
Fixes #36675
> perlPackages: cross-compilation fixes

- pkgs/applications/networking/browsers/chromium/common.nix
> chromium: fix aarch64 build

- pkgs/top-level/perl-packages.nix
To check recent ```libssh``` exploit :)
> perlPackages.NetSSHPerl: init at 2.14

- pkgs/development/interpreters/perl/default.nix
> perldevel: 5.29.3 -> 5.29.4

- pkgs/development/tools/build-managers/meson/default.nix
Fixes: #48239
@shlevy @Ericson2314 I am not sure what is going on here, but it works. Please, fix it properly
> meson: fix cross compilation of systemd

- pkgs/development/tools/misc/gnum4/default.nix
> gnum4: set platforms=all; it works on Windows

- pkgs/stdenv/generic/setup.sh
Fixes https://github.com/NixOS/nixpkgs/issues/21195
See discussion there
> [staging] substitute() print warning if does nothing

- pkgs/development/tools/phantomjs2/default.nix
> phantomjs2: fix 404 (anonscm.debian.org -> salsa.debian.org)

- pkgs/development/libraries/libvirt/default.nix
- pkgs/development/python-modules/libvirt/default.nix
- pkgs/top-level/perl-packages.nix
> libvirt: 4.7.0 -> 4.10.0

- maintainers/scripts/nix-generate-from-cpan.nix
- pkgs/applications/graphics/feh/default.nix
- pkgs/applications/misc/slic3r/default.nix
- pkgs/applications/misc/slic3r/prusa3d.nix
- pkgs/applications/networking/sieve-connect/default.nix
- pkgs/development/interpreters/perl/default.nix
- pkgs/servers/foswiki/default.nix
- pkgs/servers/monitoring/munin/default.nix
- pkgs/servers/openxpki/default.nix
- pkgs/tools/backup/znapzend/default.nix
- pkgs/tools/security/john/default.nix
- pkgs/tools/security/signing-party/default.nix
- pkgs/tools/text/popfile/default.nix
- pkgs/tools/text/schema2ldif/default.nix
- pkgs/tools/typesetting/biber/default.nix
- pkgs/top-level/all-packages.nix
- pkgs/top-level/perl-packages.nix
End-of-life upstream (https://www.cpan.org/src/README.html)
> perl526: drop

- .github/CODEOWNERS
To get notifed about the changes
Anyway I got pinged manually on anything perl-related (https://github.com/NixOS/nixpkgs/pull/44619#issuecomment-411085801, https://github.com/NixOS/nixpkgs/pull/48729#issuecomment-432682613, https://github.com/NixOS/nixpkgs/pull/48857#discussion_r233896318, ...)
> CODEOWNERS: add @volth to Perl

- pkgs/build-support/trivial-builders.nix
> linkFarm: hacky quoting -> escapeShellArg

- pkgs/tools/security/mkp224o/default.nix
- pkgs/top-level/all-packages.nix
Vanity address generator for tor onion v3 (ed25519) hidden services
> mkp224o: init at 1.2.0

- pkgs/top-level/perl-packages.nix
bulk upgrade of CPAN packages
---
> perlPackages: upgrade

- pkgs/desktops/xfce/panel-plugins/xfce4-hardware-monitor-plugin.nix
- pkgs/development/libraries/gdome2/default.nix
- pkgs/development/libraries/liblangtag/default.nix
- pkgs/development/libraries/libunique/3.x.nix
- pkgs/development/tools/misc/intel-gpu-tools/default.nix
- pkgs/tools/security/oath-toolkit/default.nix
- pkgs/top-level/all-packages.nix
fix evaluation when ```config.allowAliases``` == false
(regression after https://github.com/NixOS/nixpkgs/pull/56791)
> gnome2.gtkdoc -> gtk-doc

- pkgs/tools/misc/ipxe/default.nix
> ipxe: 20190310 -> 20190318

- pkgs/applications/audio/audio-recorder/default.nix
- pkgs/applications/misc/gnome-recipes/default.nix
- pkgs/data/themes/materia-theme/default.nix
- pkgs/desktops/mate/marco/default.nix
- pkgs/desktops/mate/mate-applets/default.nix
- pkgs/misc/themes/equilux-theme/default.nix
More like https://github.com/NixOS/nixpkgs/pull/57110 https://github.com/NixOS/nixpkgs/pull/57112
@jtojnar
> fix evaluation with `config.allowAliases = false`

- pkgs/top-level/perl-packages.nix
Update ```perl``` and ```perlPackages```
@rycee @srhb 
---
> perlPackages: mass update

- pkgs/development/interpreters/perl/default.nix
It should be in https://github.com/NixOS/nixpkgs/pull/59997 but I forgot :(
> perl-cross: update for perl 5.28.2

- pkgs/applications/virtualization/qemu/default.nix
@GrahamcOfBorg build pkgsCross.armv7l-hf-multiplatform.qemu
> qemu: fix cross

- pkgs/data/fonts/dejavu-fonts/default.nix
- pkgs/data/fonts/inconsolata/lgc.nix
- pkgs/data/fonts/libertine/default.nix
- pkgs/data/fonts/monoid/default.nix
- pkgs/data/fonts/redhat-liberation-fonts/default.nix
- pkgs/data/fonts/rictydiminished-with-firacode/default.nix
- pkgs/data/fonts/unscii/default.nix
- pkgs/data/fonts/xits-math/default.nix
it makes fonts made by ```fontforge``` **NOT** fixed-output (fixes #61212)
Lately there were 2 automated upgrades of ```fontforge``` and it introduced some chaos (https://github.com/NixOS/nixpkgs/issues/61212 https://github.com/NixOS/nixpkgs/pull/60537#issuecomment-491140568)
> data/fonts: fonts made with fontforge are not fixed-output

- pkgs/tools/misc/websocat/default.nix
websocat: add support for wss://
> websocat: add support for wss://

- nixos/modules/services/x11/desktop-managers/enlightenment.nix
- nixos/modules/services/x11/desktop-managers/pantheon.nix
- pkgs/desktops/gnome-3/default.nix
- pkgs/top-level/all-packages.nix
@jtojnar
More like #57110 #57112 #59879, it still happens
> nixos/enlightenment: fix build with config.allowAliases=false

- pkgs/applications/video/vdr/xineliboutput/default.nix
fix ```grahamcofborg-eval-package-list-no-aliases``` evaluatuon
> fix ofborg evaluations broken in #63113

- pkgs/desktops/xfce4-13/exo/default.nix
- pkgs/desktops/xfce4-13/garcon/default.nix
- pkgs/desktops/xfce4-13/libxfce4ui/default.nix
- pkgs/desktops/xfce4-13/libxfce4util/default.nix
- pkgs/desktops/xfce4-13/thunar-volman/default.nix
- pkgs/desktops/xfce4-13/thunar/default.nix
- pkgs/desktops/xfce4-13/tumbler/default.nix
- pkgs/desktops/xfce4-13/xfce4-appfinder/default.nix
- pkgs/desktops/xfce4-13/xfce4-dev-tools/default.nix
- pkgs/desktops/xfce4-13/xfce4-panel/default.nix
- pkgs/desktops/xfce4-13/xfce4-power-manager/default.nix
- pkgs/desktops/xfce4-13/xfce4-session/default.nix
- pkgs/desktops/xfce4-13/xfce4-settings/default.nix
- pkgs/desktops/xfce4-13/xfconf/default.nix
- pkgs/desktops/xfce4-13/xfdesktop/default.nix
- pkgs/desktops/xfce4-13/xfwm4/default.nix
version bump
@yegortimoshenko @romildo
> xfce4-13: 4.14pre1 -> 4.14pre2

- pkgs/top-level/perl-packages.nix
It should fix https://github.com/NixOS/nixpkgs/pull/64157#issuecomment-510473907
@ajs124
> perlPackages.{EmailSender,FileFindObjectRule}: fix tests

- pkgs/top-level/perl-packages.nix
Adopt python's change from https://github.com/NixOS/nixpkgs/pull/61139
There is currently no bug to fix, it just makes the things more consistent and prevents hitting the bug in the future
> perl-packages: Set perlPackages attr in perlPackages scope

- pkgs/development/interpreters/perl/default.nix
- pkgs/development/interpreters/perl/no-sys-dirs-5.31.patch
> perldevel: 5.30.0 -> 5.31.2

- pkgs/development/compilers/scala/2.12.nix
> scala_2_12: 2.12.8 -> 2.12.9

- pkgs/desktops/xfce4-14/exo/default.nix
- pkgs/desktops/xfce4-14/garcon/default.nix
- pkgs/desktops/xfce4-14/gigolo/default.nix
- pkgs/desktops/xfce4-14/libxfce4ui/default.nix
- pkgs/desktops/xfce4-14/libxfce4util/default.nix
- pkgs/desktops/xfce4-14/mkXfceDerivation.nix
- pkgs/desktops/xfce4-14/mousepad/default.nix
- pkgs/desktops/xfce4-14/orage/default.nix
- pkgs/desktops/xfce4-14/parole/default.nix
- pkgs/desktops/xfce4-14/ristretto/default.nix
- pkgs/desktops/xfce4-14/thunar-volman/default.nix
- pkgs/desktops/xfce4-14/thunar/default.nix
- pkgs/desktops/xfce4-14/tumbler/default.nix
- pkgs/desktops/xfce4-14/xfburn/default.nix
- pkgs/desktops/xfce4-14/xfce4-appfinder/default.nix
- pkgs/desktops/xfce4-14/xfce4-dev-tools/default.nix
- pkgs/desktops/xfce4-14/xfce4-notifyd/default.nix
- pkgs/desktops/xfce4-14/xfce4-panel/default.nix
- pkgs/desktops/xfce4-14/xfce4-power-manager/default.nix
- pkgs/desktops/xfce4-14/xfce4-screenshooter/default.nix
- pkgs/desktops/xfce4-14/xfce4-session/default.nix
- pkgs/desktops/xfce4-14/xfce4-settings/default.nix
- pkgs/desktops/xfce4-14/xfce4-terminal/default.nix
- pkgs/desktops/xfce4-14/xfce4-volumed-pulse/default.nix
- pkgs/desktops/xfce4-14/xfce4-whiskermenu-plugin/default.nix
- pkgs/desktops/xfce4-14/xfconf/default.nix
- pkgs/desktops/xfce4-14/xfdesktop/default.nix
- pkgs/desktops/xfce4-14/xfwm4/default.nix
> xfce4-14: 4.14.pre2 -> 4.14

- pkgs/development/compilers/graalvm/enterprise-edition.nix
- pkgs/top-level/all-packages.nix
Added non-free version, which supposes to work faster than the free version from https://github.com/NixOS/nixpkgs/pull/61475
cc @hlolli @NeQuissimus
> graalvm8-ee: init at 19.1.1

- pkgs/development/java-modules/jogl/default.nix
#37364 seems to be fixed so the workaround is not needed
cc @d-goldin @lopsided98
> jogl: remove #37364 workaround

- pkgs/development/tools/ammonite/default.nix
- pkgs/top-level/all-packages.nix
add version compiled with scala-2.13
> ammonite: add scala-2.13 version

- pkgs/top-level/perl-packages.nix
Update perlPackages
Tested on `x86_64-linux` and `aarch64-linux` (`i686-linux` is still building)
It cherry-picks https://github.com/NixOS/nixpkgs/pull/66459 and https://github.com/NixOS/nixpkgs/pull/71579 as the first two commits to avoid supporting all possible orders in which the PRs could be merged.
cc @stigtsp @aanderse @srhb @rycee
> perlPackages: bulk upgrade

- pkgs/development/compilers/oraclejdk/jdk-linux-base.nix
I got tired seeing this sh.. in the logs
related https://github.com/NixOS/nixpkgs/pull/54269
> oraclejdk8: remove warning

- pkgs/development/interpreters/perl/default.nix
- pkgs/top-level/perl-packages.nix
> perl: 5.30.0 -> 5.30.1

- pkgs/development/compilers/graalvm/enterprise-edition.nix
Update non-free version of GraalVM.
> graalvm{8,11}-ee: 19.3.1 -> 20.0.0

- nixos/tests/kubernetes/dns.nix
> tests/kubernetes: remove unreferenced variable and import from inexisting file

- pkgs/development/libraries/libwebsockets/default.nix
- pkgs/top-level/all-packages.nix
`3.2.0 -> 3.2.2` solved my problems with 3.1 -> 3.2 transition, and it probably solves https://github.com/NixOS/nixpkgs/issues/68588
cc @peterhoeg @ralight
> libwebsockets: 3.2.0 -> 3.2.2; init as 4.0.0

- pkgs/development/interpreters/perl/default.nix
> perl: 5.30.2 -> 5.30.3

- pkgs/applications/editors/jedit/default.nix
- pkgs/applications/version-management/git-and-tools/bfg-repo-cleaner/default.nix
- pkgs/build-support/fetchmavenartifact/default.nix
- pkgs/build-support/fetchurl/mirrors.nix
- pkgs/development/interpreters/clojurescript/lumo/deps.nix
- pkgs/servers/monitoring/prometheus/jmx-httpserver.nix
- pkgs/tools/networking/openapi-generator-cli/default.nix
> [20.03] treewide: central.maven.org -> repo1.maven.org

- nixos/modules/tasks/network-interfaces.nix
> nixos/networking: Enhance hostId description

- pkgs/development/perl-modules/xml-parser-0001-HACK-Assumes-Expat-paths-are-good.patch
- pkgs/top-level/perl-packages.nix
update `perlPackages.*`
successfully built on `x86_64-linux` and `aarch64-linux`
> perlPackages: bulk update

- pkgs/development/perl-modules/xml-parser-0001-HACK-Assumes-Expat-paths-are-good.patch
- pkgs/top-level/perl-packages.nix
https://github.com/NixOS/nixpkgs/pull/97098 rebased to `staging-20.09`
> [staging-20.09] perlPackages: bulk update

- pkgs/top-level/all-packages.nix
`pkgs.config` looks like a typo
> all-packages.nix: pkgs.config.cudaSupport -> config.cudaSupport

- pkgs/development/compilers/graalvm/enterprise-edition.nix
> graalvm8-ee, graalvm11-ee: 20.0.0 -> 20.2.1

- pkgs/tools/networking/q/default.nix
[Changelog](https://github.com/natesales/q/releases/tag/v0.8.4)
- made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generat …
> q: 0.8.2 -> 0.8.4

- pkgs/applications/misc/safeeyes/default.nix
https://github.com/slgobinath/SafeEyes/commit/ea2c74797804736cb43d7b1bd991ad9396a4eb19
https://github.com/NixOS/nixpkgs/pull/332938#issuecomment-2273830073
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
- made sure NixOS …
> safeeyes: libappindicator-gtk3 is no longer a buildInput

- nixos/modules/programs/zsh/oh-my-zsh.nix
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
- made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [24.11 …
> oh-my-zsh: add 'preLoaded' option

- nixos/modules/programs/zsh/oh-my-zsh.nix
I made a mistake
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
- made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant …
> oh-my-zsh: fix 'preLoaded' option documentation

- pkgs/by-name/yo/youtubeuploader/package.nix
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
- made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [25.05 …
> youtubeuploader: init at 1.24.4

- pkgs/development/python-modules/paddlex/default.nix
> python313Packages.paddlex: 3.1.1 -> 3.1.3

- maintainers/maintainer-list.nix
- pkgs/applications/editors/vscode/extensions/default.nix
- pkgs/applications/editors/vscode/extensions/ufo5260987423.magic-scheme/default.nix
This extension adds support for Scheme(r6rs standard) to VS Code. https://github.com/ufo5260987423/magic-scheme …
> vscode-extensions.ufo5260987423.magic-scheme: init at 0.0.5

- pkgs/applications/editors/vscode/extensions/ms-python.python/default.nix
> vscode-extensions.ms-python.python: fix hash

- pkgs/development/compilers/flutter/update/update.py
- pkgs/development/compilers/flutter/versions/3_32/data.json
https://github.com/flutter/flutter/blob/master/CHANGELOG.md#3327 …
> flutter332: 3.32.6 -> 3.32.7

- pkgs/by-name/fn/fna3d/package.nix
- pkgs/by-name/r1/r10k/package.nix
- pkgs/by-name/xp/xpipe/package.nix
> fna3d, r10k, xpipe: hardcoded meta.mainProgram

- pkgs/by-name/ar/ardopc/package.nix
- pkgs/by-name/co/colormake/package.nix
- pkgs/by-name/cr/croaring/package.nix
- pkgs/by-name/cu/cups-zj-58/package.nix
- pkgs/by-name/de/dec-decode/package.nix
- pkgs/by-name/em/emojipick/package.nix
- pkgs/by-name/if/ifdnfc/package.nix
- pkgs/by-name/li/liberal-crime-squad/package.nix
- pkgs/by-name/ls/lssecret/package.nix
- pkgs/by-name/op/openmolcas/package.nix
- pkgs/by-name/pa/pax-britannica/package.nix
- pkgs/by-name/pg/pgpkeyserver-lite/package.nix
- pkgs/development/compilers/opensmalltalk-vm/default.nix
- pkgs/development/python-modules/worldengine/default.nix
- pkgs/os-specific/linux/xpad-noone/default.nix
- pkgs/top-level/haxe-packages.nix
> treewide: update rev to full-length commit

- pkgs/by-name/wi/windsend/gitHashes.json
- pkgs/by-name/wi/windsend/package.nix
- pkgs/by-name/wi/windsend/pubspec.lock.json
- pkgs/by-name/wi/windsend/update-gitHashes.py
- pkgs/by-name/wi/windsend/update.sh
https://github.com/doraemonkeys/WindSend/releases/tag/v1.5.5
https://github.com/doraemonkeys/WindSend/compare/v1.5.4...v1.5.5 …
> windsend: 1.5.4 -> 1.5.5

- pkgs/applications/editors/vscode/extensions/default.nix
- pkgs/applications/editors/vscode/extensions/oliver-ni.scheme-fmt/default.nix
Formats Scheme source code. https://github.com/oliver-ni/scheme-fmt …
> vscode-extensions.oliver-ni.scheme-fmt: init at 1.2.1

- pkgs/by-name/wi/windsend-rs/package.nix
https://github.com/doraemonkeys/WindSend/releases/tag/v1.5.5
https://github.com/doraemonkeys/WindSend/compare/v1.5.4...v1.5.5 …
> windsend-rs: 1.5.4 -> 1.5.5

- pkgs/by-name/sa/saber/gitHashes.json
- pkgs/by-name/sa/saber/package.nix
- pkgs/by-name/sa/saber/pubspec.lock.json
- pkgs/by-name/sa/saber/update-gitHashes.py
https://github.com/saber-notes/saber/releases/tag/v0.26.0
https://github.com/saber-notes/saber/compare/v0.25.9...v0.26.0 …
> saber: 0.25.9 -> 0.26.0

- pkgs/development/compilers/flutter/versions/3_32/data.json
https://github.com/flutter/flutter/blob/master/CHANGELOG.md#3328
https://github.com/flutter/flutter/releases/tag/3.32.8
https://github.com/flutter/flutter/compare/3.32.7...3.32.8
[nixos/tests]: …
> flutter332: 3.32.7 -> 3.32.8

- pkgs/by-name/bi/bitcomet/package.nix
> bitcomet: 2.13.2 -> 2.15.0

- pkgs/by-name/au/auto-cpufreq/package.nix
> auto-cpufreq: set pyproject and refactor

- pkgs/by-name/ti/tinystatus/package.nix
> tinystatus: refactor

- pkgs/by-name/su/sunshine/package.nix
- pkgs/by-name/su/sunshine/updater.sh
Optimize update script
[pkgs/test]: …
> sunshine: refactor

- pkgs/by-name/po/postman/darwin.nix
- pkgs/by-name/po/postman/linux.nix
- pkgs/by-name/po/postman/package.nix
> postman: 11.50.5 -> 11.56.4

- pkgs/by-name/to/todoist-electron/package.nix
> todoist-electron: 9.8.0 -> 9.18.0

- pkgs/by-name/ne/newelle/package.nix
Diff: https://github.com/qwersyk/Newelle/compare/refs/tags/0.9.8...refs/tags/1.0.0
https://github.com/qwersyk/Newelle/releases/tag/1.0.0 …
> newelle: 0.9.8 -> 1.0.0

- pkgs/applications/editors/vscode/extensions/default.nix
- pkgs/applications/editors/vscode/extensions/ndonfris.fish-lsp/default.nix
LSP implementation for the fish shell language 🐠 . https://github.com/ndonfris/fish-lsp …
> vscode-extensions.ndonfris.fish-lsp: init at 0.1.10

- pkgs/applications/editors/vscode/vscode.nix
> vscode: remove misleading description and rec

- pkgs/by-name/wa/waydroid-helper/package.nix
https://github.com/ayasa520/waydroid-helper/releases/tag/v0.2.3
https://github.com/ayasa520/waydroid-helper/compare/v0.1.2...v0.2.3 …
> waydroid-helper: 0.1.2 -> 0.2.3

- pkgs/development/python-modules/coconut/default.nix
- pkgs/top-level/all-packages.nix
> coconut: fix build
